package com.ystech.xwqr.set.model;

// Generated 2014-2-17 20:12:44 by Hibernate Tools 4.0.0

/**
 * Carmodel generated by hbm2java
 */
public class CarModel implements java.io.Serializable {
	public static int STATUSSTOP=2;
	public static int STATUSCOMM=1;
	
	private Integer dbid;
	private CarSeriy carseries;
	private String name;
	private Brand brand;
	private String yearModel;
	private Long navPrice;
	private Long salePrice;
	//销售顾问结算价
	private Long saleCSPrice;
	//历史结算价
	private Long historyCSPrice;
	private String picture;
	private Integer displacementNum;
	private Integer gearNum;
	private String transmission;
	private String content;
	private Integer orderNum;
	private Integer businessId;
	private Integer status;
	private Integer enterpriseId;
	public CarModel() {
	}

	public CarModel(CarSeriy carseries, String name, Integer brandId,
			String yearModel, Long navPrice, Long salePrice, String picture,
			Integer displacementNum, Integer gearNum, String transmission,
			String content, Integer orderNum) {
		this.carseries = carseries;
		this.name = name;
		this.yearModel = yearModel;
		this.navPrice = navPrice;
		this.salePrice = salePrice;
		this.picture = picture;
		this.displacementNum = displacementNum;
		this.gearNum = gearNum;
		this.transmission = transmission;
		this.content = content;
		this.orderNum = orderNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public CarSeriy getCarseries() {
		return this.carseries;
	}

	public void setCarseries(CarSeriy carseries) {
		this.carseries = carseries;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public String getYearModel() {
		return this.yearModel;
	}

	public void setYearModel(String yearModel) {
		this.yearModel = yearModel;
	}

	public Long getNavPrice() {
		return this.navPrice;
	}

	public void setNavPrice(Long navPrice) {
		this.navPrice = navPrice;
	}

	public Long getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Long salePrice) {
		this.salePrice = salePrice;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Integer getDisplacementNum() {
		return this.displacementNum;
	}

	public void setDisplacementNum(Integer displacementNum) {
		this.displacementNum = displacementNum;
	}

	public Integer getGearNum() {
		return this.gearNum;
	}

	public void setGearNum(Integer gearNum) {
		this.gearNum = gearNum;
	}

	public String getTransmission() {
		return this.transmission;
	}

	public void setTransmission(String transmission) {
		this.transmission = transmission;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getBusinessId() {
		return businessId;
	}

	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getSaleCSPrice() {
		return saleCSPrice;
	}

	public void setSaleCSPrice(Long saleCSPrice) {
		this.saleCSPrice = saleCSPrice;
	}

	public Long getHistoryCSPrice() {
		return historyCSPrice;
	}

	public void setHistoryCSPrice(Long historyCSPrice) {
		this.historyCSPrice = historyCSPrice;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	
}
