package com.ystech.xwqr.set.model;

// Generated 2016-4-26 14:07:29 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Carmodelsalepolicyhistory generated by hbm2java
 */
public class CarModelSalePolicyHistory implements java.io.Serializable {

	private Integer dbid;
	private Date createDate;
	private Long saleCsprice;
	private Long areaSaleCsprice;
	private Long netSaleCsprice;
	private Integer carModelSalePolicyId;

	public CarModelSalePolicyHistory() {
	}

	public CarModelSalePolicyHistory(Date createDate, Long saleCsprice) {
		this.createDate = createDate;
		this.saleCsprice = saleCsprice;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getSaleCsprice() {
		return this.saleCsprice;
	}

	public void setSaleCsprice(Long saleCsprice) {
		this.saleCsprice = saleCsprice;
	}

	public Integer getCarModelSalePolicyId() {
		return carModelSalePolicyId;
	}

	public void setCarModelSalePolicyId(Integer carModelSalePolicyId) {
		this.carModelSalePolicyId = carModelSalePolicyId;
	}

	public Long getAreaSaleCsprice() {
		return areaSaleCsprice;
	}

	public void setAreaSaleCsprice(Long areaSaleCsprice) {
		this.areaSaleCsprice = areaSaleCsprice;
	}

	public Long getNetSaleCsprice() {
		return netSaleCsprice;
	}

	public void setNetSaleCsprice(Long netSaleCsprice) {
		this.netSaleCsprice = netSaleCsprice;
	}
	

}
