package com.ystech.xwqr.set.model;

// Generated 2014-2-17 20:12:44 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Carseries generated by hbm2java
 */
public class CarSeriy implements java.io.Serializable {
	public static int STATUSSTOP=2;
	public static int STATUSCOMM=1;
	public static int TRY_CARYES=1;
	public static int TRY_CARNO=2;
	private Integer dbid;
	private String name;
	private Brand brand;
	private String introduction;
	private String picture;
	private Integer orderNum;
	private Long navPrice;
	private Long salePrice;
	//销售顾问结算价
	private Long saleCSPrice;
	private String description;
	//项目名称
	private Integer itemType;
	//车辆颜色
	private String carColors;
	//车辆级别
	private String carLevel;
	//价格区间
	private String priceFrom;
	//提车时间
	private String handCarTime;
	//变速箱类型
	private String bianxueType;
	//汽车动力类型
	private String carDriverType;
	//是否进口
	private String hasJk;
	//质保类型
	private String zbType;
	//排量
	private String pailiang;
	//是否有试驾车:1、有试驾车；2、无试驾车
	private Integer tryCarStatus;
	//优惠信息
	private String discInfor;
	private Set carmodels = new HashSet(0);
	private Integer status;
	private Integer enterpriseId;
	public String getCarColors() {
		return carColors;
	}

	public void setCarColors(String carColors) {
		this.carColors = carColors;
	}

	public String getCarLevel() {
		return carLevel;
	}

	public void setCarLevel(String carLevel) {
		this.carLevel = carLevel;
	}

	public String getPriceFrom() {
		return priceFrom;
	}

	public void setPriceFrom(String priceFrom) {
		this.priceFrom = priceFrom;
	}

	public String getHandCarTime() {
		return handCarTime;
	}

	public void setHandCarTime(String handCarTime) {
		this.handCarTime = handCarTime;
	}

	public String getBianxueType() {
		return bianxueType;
	}

	public void setBianxueType(String bianxueType) {
		this.bianxueType = bianxueType;
	}

	public String getCarDriverType() {
		return carDriverType;
	}

	public void setCarDriverType(String carDriverType) {
		this.carDriverType = carDriverType;
	}

	public String getHasJk() {
		return hasJk;
	}

	public void setHasJk(String hasJk) {
		this.hasJk = hasJk;
	}

	public String getZbType() {
		return zbType;
	}

	public void setZbType(String zbType) {
		this.zbType = zbType;
	}

	public String getPailiang() {
		return pailiang;
	}

	public void setPailiang(String pailiang) {
		this.pailiang = pailiang;
	}
	public CarSeriy() {
	}

	public CarSeriy(String name, Integer brandId, String introduction,
			String picture, Integer orderNum, String description, Set carmodels) {
		this.name = name;
		this.introduction = introduction;
		this.picture = picture;
		this.orderNum = orderNum;
		this.description = description;
		this.carmodels = carmodels;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getCarmodels() {
		return this.carmodels;
	}

	public void setCarmodels(Set carmodels) {
		this.carmodels = carmodels;
	}


	public Integer getItemType() {
		return itemType;
	}

	public void setItemType(Integer itemType) {
		this.itemType = itemType;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getNavPrice() {
		return navPrice;
	}

	public void setNavPrice(Long navPrice) {
		this.navPrice = navPrice;
	}

	public Long getSalePrice() {
		return salePrice;
	}

	public void setSalePrice(Long salePrice) {
		this.salePrice = salePrice;
	}

	public Long getSaleCSPrice() {
		return saleCSPrice;
	}

	public void setSaleCSPrice(Long saleCSPrice) {
		this.saleCSPrice = saleCSPrice;
	}
	public Integer getTryCarStatus() {
		return tryCarStatus;
	}

	public void setTryCarStatus(Integer tryCarStatus) {
		this.tryCarStatus = tryCarStatus;
	}

	public String getDiscInfor() {
		return discInfor;
	}

	public void setDiscInfor(String discInfor) {
		this.discInfor = discInfor;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}
	
}
