package com.ystech.xwqr.set.model;

// Generated 2015-1-8 16:56:38 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * 功能描述：优惠基础项
 * SPreferenceitem generated by hbm2java
 */
public class PreferenceItem implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private Integer netTowType;
	private String note;
	private Integer orderNum;
	private Integer defaultPrice;
	private Date createDate;
	private Date modifyDate;
	private String jym;

	public PreferenceItem() {
	}

	public PreferenceItem(String name, Integer type, String note,
			Integer orderNum, Date createDate, Date modifyDate) {
		this.name = name;
		this.note = note;
		this.orderNum = orderNum;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}



	public Integer getNetTowType() {
		return netTowType;
	}

	public void setNetTowType(Integer netTowType) {
		this.netTowType = netTowType;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getDefaultPrice() {
		return defaultPrice;
	}

	public void setDefaultPrice(Integer defaultPrice) {
		this.defaultPrice = defaultPrice;
	}

	public String getJym() {
		return jym;
	}

	public void setJym(String jym) {
		this.jym = jym;
	}
	
}
