package com.ystech.qywx.model;

// Generated 2016-7-26 10:40:22 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QywxAct generated by hbm2java
 */
public class Act implements java.io.Serializable {
	private Integer dbid;
	private String name;
	private String note;
	private Date createDate;
	private Date modifyDate;
	private Set actEnterprises = new HashSet(0);

	public Act() {
	}

	public Act(String name, String note, Date createDate, Date modifyDate,
			Integer status, Set qywxActenterprises) {
		this.name = name;
		this.note = note;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}


	public Set getActEnterprises() {
		return actEnterprises;
	}

	public void setActEnterprises(Set actEnterprises) {
		this.actEnterprises = actEnterprises;
	}



}
