package com.ystech.qywx.model;

// Generated 2015-2-13 10:48:23 by Hibernate Tools 4.0.0

/**
 * WechatenterpriseApp generated by hbm2java
 */
public class App implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String intro;
	private String userIds;
	private String token;
	private String encodingAeskey;
	private Integer appId;
	private String square_logo_url;
	private String round_logo_url;

	public App() {
	}

	public App(String name, String intro, String userIds,
			String token, String encodingAeskey, Integer appId) {
		this.name = name;
		this.intro = intro;
		this.userIds = userIds;
		this.token = token;
		this.encodingAeskey = encodingAeskey;
		this.appId = appId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getUserIds() {
		return this.userIds;
	}

	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getEncodingAeskey() {
		return this.encodingAeskey;
	}

	public void setEncodingAeskey(String encodingAeskey) {
		this.encodingAeskey = encodingAeskey;
	}

	public Integer getAppId() {
		return this.appId;
	}

	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	public String getSquare_logo_url() {
		return square_logo_url;
	}

	public void setSquare_logo_url(String square_logo_url) {
		this.square_logo_url = square_logo_url;
	}

	public String getRound_logo_url() {
		return round_logo_url;
	}

	public void setRound_logo_url(String round_logo_url) {
		this.round_logo_url = round_logo_url;
	}

}
