package com.ystech.qywx.model;

// Generated 2016-5-31 17:18:22 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.xwqr.model.sys.Department;
import com.ystech.xwqr.model.sys.Enterprise;

/**
 * QywxAppdepartment generated by hbm2java
 */
public class AppDepartment implements java.io.Serializable {

	private Integer dbid;
	private Department department;
	private Enterprise enterprise;
	private Date createDate;
	private Date modifyDate;
	private App app;

	public AppDepartment() {
	}

	public AppDepartment(Integer departmentId, Integer enterpriseId,
			Date createDate, Date modifyDate, Integer appId) {
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Enterprise getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

	public App getApp() {
		return app;
	}

	public void setApp(App app) {
		this.app = app;
	}


}
