package com.ystech.qywx.model;

// Generated 2016-5-31 10:33:55 by Hibernate Tools 4.0.0

/**
 * QywxAppmenu generated by hbm2java
 */
public class AppMenu implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String url;
	private String keyValue;
	private String type;
	private AppMenu parent;
	private App app;
	private Integer orders;

	public AppMenu() {
	}

	public AppMenu(String name, String url, String key, String type,
			Integer parentId, Integer appId, Integer orders) {
		this.name = name;
		this.url = url;
		this.type = type;
		this.orders = orders;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}


	public String getKeyValue() {
		return keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}


	public AppMenu getParent() {
		return parent;
	}

	public void setParent(AppMenu parent) {
		this.parent = parent;
	}

	public App getApp() {
		return app;
	}

	public void setApp(App app) {
		this.app = app;
	}

	public Integer getOrders() {
		return this.orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

}
