package com.ystech.qywx.model;

import com.ystech.xwqr.model.sys.User;

// Generated 2016-7-23 10:47:18 by Hibernate Tools 4.0.0

/**
 * QywxAppuserroleper generated by hbm2java
 */
public class AppUserRolePer implements java.io.Serializable {

	private int dbid;
	//权限用户
	private AppUserRole appUserRole;
	//红包配比人员
	private User user;
	//红包配比人员姓名
	private String userName;
	//配比百分比
	private Integer per;
	//配比级别
	private Integer num;

	public AppUserRolePer() {
	}

	public AppUserRolePer(int dbid) {
		this.dbid = dbid;
	}

	public AppUserRolePer(int dbid, AppUserRole qywxAppuserrole,
			Integer userDbid, String userName, Integer per) {
		this.dbid = dbid;
		this.userName = userName;
		this.per = per;
	}

	public int getDbid() {
		return this.dbid;
	}

	public void setDbid(int dbid) {
		this.dbid = dbid;
	}


	public AppUserRole getAppUserRole() {
		return appUserRole;
	}

	public void setAppUserRole(AppUserRole appUserRole) {
		this.appUserRole = appUserRole;
	}


	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getPer() {
		return this.per;
	}

	public void setPer(Integer per) {
		this.per = per;
	}

}
