package com.ystech.qywx.model;

// Generated 2016-7-23 10:47:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.ystech.xwqr.model.sys.Department;
import com.ystech.xwqr.model.sys.User;

/**
 * QywxAppuserrole generated by hbm2java
 */
public class AppUserRole implements java.io.Serializable {

	private Integer dbid;
	
	private Department department;
	//userId
	private String userId;
	//用户姓名
	private String userName;
	//用户
	private User user;
	//占比
	private Integer userPer;
	private Set appUserRolePers = new HashSet(0);

	public AppUserRole() {
	}

	public AppUserRole(Integer departmentId, String userId,
			String userName, Integer userDbid, Set qywxAppuserrolepers) {
		this.userId = userId;
		this.userName = userName;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}


	public Set getAppUserRolePers() {
		return appUserRolePers;
	}

	public void setAppUserRolePers(Set appUserRolePers) {
		this.appUserRolePers = appUserRolePers;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getUserPer() {
		return userPer;
	}

	public void setUserPer(Integer userPer) {
		this.userPer = userPer;
	}



}
