package com.ystech.qywx.model;

// Generated 2015-3-12 10:05:19 by Hibernate Tools 4.0.0

/**
 * QywxMessagetemplate generated by hbm2java
 */
public class MessageTemplate implements java.io.Serializable {

	private Integer dbid;
	private String userIds;
	private String userNames;
	private String msgtype;
	private App app;
	private String title;
	private String description;
	private String url;
	private String picurl;
	private MessageTemplateType messageTemplateType;

	public MessageTemplate() {
	}

	public MessageTemplate(String touser, String msgtype, String agentid,
			String title, String description, String url, String picurl,
			Integer type) {
		this.msgtype = msgtype;
		this.title = title;
		this.description = description;
		this.url = url;
		this.picurl = picurl;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}


	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPicurl() {
		return this.picurl;
	}

	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	public MessageTemplateType getMessageTemplateType() {
		return messageTemplateType;
	}

	public void setMessageTemplateType(MessageTemplateType messageTemplateType) {
		this.messageTemplateType = messageTemplateType;
	}

	public String getUserIds() {
		return userIds;
	}

	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}

	public String getUserNames() {
		return userNames;
	}

	public void setUserNames(String userNames) {
		this.userNames = userNames;
	}

	public App getApp() {
		return app;
	}

	public void setApp(App app) {
		this.app = app;
	}
}
