package com.ystech.qywx.model;

// Generated 2016-5-31 15:30:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * QywxMessagetemplatetype generated by hbm2java
 */
public class MessageTemplateType implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String note;
	private Integer orderNum;
	private Date createDate;
	private Date modifyDate;

	public MessageTemplateType() {
	}

	public MessageTemplateType(String name, String note, Integer orderNum,
			Date createDate, Date modifyDate) {
		this.name = name;
		this.note = note;
		this.orderNum = orderNum;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
