package com.ystech.qywx.model;

// Generated 2016-7-21 15:46:10 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.xwqr.model.sys.Enterprise;

/**
 * QywxRedbag generated by hbm2java
 */
public class RedBag implements java.io.Serializable {

	public static final Integer COMM = 1;
	public static final Integer FUAIL = 2;
	public static final Integer SUCCESS = 3;
	
	public static final Integer REDENTERPRISE = 1;
	public static final Integer REDWECHAT=2;
	private Integer dbid;
	//接收人ID，交车红包为用户ID，经纪人为会员ID
	private Integer recipientId;
	//接收人姓名
	private String recipientName;
	//公司Id
	private Enterprise enterprise;
	//创建时间
	private Date createDate;
	//创建人
	private String creator;
	//发送时间
	private Date sendTime;
	//返回状态
	private Integer turnBackStatus;
	//上户订单号 商户订单号（每个订单号必须唯一）组成：yyyymmdd+10位一天内不能重复的数字。
	private String billno;
	//接受红包OPenId
	private String openId;
	//祝福语
	private String wishing;
	//备注
	private String remark;
	//活动名称
	private String actName;
	//对应appId
	private String appId;
	//红包金额
	private Double redBagMoney;
	//红包说明
	private String note;
	//服务器IP
	private String ip;
	//总金额
	private Double totalMoney;
	//数据 
	private Integer num;
	//红包类型：1、企业内部奖励红包；2、公众号红包
	private Integer redType;
	////////////////////企业内部奖励红包 单独拥有字段//////////////////////
	//客户ID
	private Integer customerId;
	//部门ID
	private Integer departmentId;
	
	
    ////////////////////公众单独 单独拥有字段//////////////////////
	private Integer rewardId;
	
	public RedBag() {
	}

	public RedBag(Integer userId, String userName, Double redBagMoney,
			Integer enterpriseId, Date sendTime, Integer customerId,
			String customerName, Integer factoryId, String carModel,
			String vinCode, Date createDate, String creator,
			Integer turnBackStatus) {
		this.redBagMoney = redBagMoney;
		this.sendTime = sendTime;
		this.createDate = createDate;
		this.creator = creator;
		this.turnBackStatus = turnBackStatus;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public Double getRedBagMoney() {
		return this.redBagMoney;
	}

	public void setRedBagMoney(Double redBagMoney) {
		this.redBagMoney = redBagMoney;
	}


	public Enterprise getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}


	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Integer getTurnBackStatus() {
		return this.turnBackStatus;
	}

	public void setTurnBackStatus(Integer turnBackStatus) {
		this.turnBackStatus = turnBackStatus;
	}

	public String getBillno() {
		return billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public String getWishing() {
		return wishing;
	}

	public void setWishing(String wishing) {
		this.wishing = wishing;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getActName() {
		return actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}

	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Double getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Integer getRecipientId() {
		return recipientId;
	}

	public void setRecipientId(Integer recipientId) {
		this.recipientId = recipientId;
	}

	public String getRecipientName() {
		return recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public Integer getRedType() {
		return redType;
	}

	public void setRedType(Integer redType) {
		this.redType = redType;
	}

	public Integer getRewardId() {
		return rewardId;
	}

	public void setRewardId(Integer rewardId) {
		this.rewardId = rewardId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "RedBag [dbid=" + dbid + ", recipientId=" + recipientId
				+ ", recipientName=" + recipientName + ", enterprise="
				+ enterprise + ", createDate=" + createDate + ", creator="
				+ creator + ", sendTime=" + sendTime + ", turnBackStatus="
				+ turnBackStatus + ", billno=" + billno + ", openId=" + openId
				+ ", wishing=" + wishing + ", remark=" + remark + ", actName="
				+ actName + ", appId=" + appId + ", redBagMoney=" + redBagMoney
				+ ", note=" + note + ", ip=" + ip + ", totalMoney="
				+ totalMoney + ", num=" + num + ", redType=" + redType
				+ ", customerId=" + customerId + ", departmentId="
				+ departmentId + ", rewardId=" + rewardId + "]";
	}
	
}
