package com.ystech.pllm.model;
// Generated 2016-8-19 22:40:49 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * PllmRecPagerecord generated by hbm2java
 */
public class RecPageRecord implements java.io.Serializable {
	private Integer dbid;
	private RecPageUrl recPageUrl;
	//关注用户ID
	private Integer gzUserId;
	//访问开始时间
	private Date startTime;
	//访问结束时间
	private Date liveTime;
	//停留时间
	private Integer staLone;
	//访问IP
	private String ip;
	//访问所在区域
	private String areaStr;
	//城市
	private String city;
	//省份
	private String provice;
	//sessionId
	private String sessionId;
	//1、内部访问；2、外部访问
	private Integer type;
	//商品ID
	private Integer productId;

	public RecPageRecord() {
	}


	public RecPageRecord(int dbid, RecPageUrl pllmRecPageurl, Integer gzUserId, Date startTime, Date liveTime,
			Integer staLone, Integer ip, String areaStr, String city, String provice) {
		this.gzUserId = gzUserId;
		this.startTime = startTime;
		this.liveTime = liveTime;
		this.staLone = staLone;
		this.areaStr = areaStr;
		this.city = city;
		this.provice = provice;
	}

	public Integer getDbid() {
		return dbid;
	}


	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public RecPageUrl getRecPageUrl() {
		return recPageUrl;
	}

	public void setRecPageUrl(RecPageUrl recPageUrl) {
		this.recPageUrl = recPageUrl;
	}

	public Integer getGzUserId() {
		return this.gzUserId;
	}

	public void setGzUserId(Integer gzUserId) {
		this.gzUserId = gzUserId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getLiveTime() {
		return this.liveTime;
	}

	public void setLiveTime(Date liveTime) {
		this.liveTime = liveTime;
	}

	public Integer getStaLone() {
		return this.staLone;
	}

	public void setStaLone(Integer staLone) {
		this.staLone = staLone;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getAreaStr() {
		return this.areaStr;
	}

	public void setAreaStr(String areaStr) {
		this.areaStr = areaStr;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvice() {
		return this.provice;
	}

	public void setProvice(String provice) {
		this.provice = provice;
	}


	public String getSessionId() {
		return sessionId;
	}


	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}


	public Integer getType() {
		return type;
	}


	public void setType(Integer type) {
		this.type = type;
	}


	public Integer getProductId() {
		return productId;
	}


	public void setProductId(Integer productId) {
		this.productId = productId;
	}
	
}
