package com.ystech.pllm.model;

// Generated 2014-4-30 12:02:25 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.mem.model.Member;

/**
 * Sharerecord generated by hbm2java
 */
public class RecShareRecord implements java.io.Serializable {
	public static Integer TYPEINDEX=1;
	public static Integer TYPECOUPON=2;
	public static Integer TYPEACTIVITY=3;
	public static Integer TYPEACTIVITYDET=4;
	public static Integer TYPEPRODCUT=5;
	private Integer dbid;
	//微信Id
	private String wechatId;
	//分享时间
	private Date shareTime;
	//会员
	private Member member;
	//分享项目
	private String project;
	//分享备注
	private String note;
	//1、商城分享；2、优惠券分享；3、活动分享；4、单个活动分享；5、商品分享
	private int type;

	public RecShareRecord() {
	}

	public RecShareRecord(int dbid) {
		this.dbid = dbid;
	}

	public RecShareRecord(int dbid, String wechatId,
			Integer memberId, Date shareTime) {
		this.dbid = dbid;
		this.wechatId = wechatId;
		this.shareTime = shareTime;
	}



	public Integer getDbid() {
		return dbid;
	}

	public String getWechatId() {
		return this.wechatId;
	}

	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}


	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getShareTime() {
		return this.shareTime;
	}

	public void setShareTime(Date shareTime) {
		this.shareTime = shareTime;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
