package com.ystech.pllm.model;
// Generated 2016-8-19 22:40:49 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * PllmRecVisitrecord generated by hbm2java
 */
public class RecVisitRecord implements java.io.Serializable {

	private Integer dbid;
	//关注用户Id
	private Integer gzUserId;
	//访问开始时间
	private Date startTime;
	//离开时间
	private Date leaveTime;
	//停留时间
	private Integer timeLong;
	//访问IP
	private String ip;
	//所在区域
	private String areaStr;
	//城市
	private String city;
	//省份
	private String provice;
	//sessionId
	private String sessionId;

	public RecVisitRecord() {
	}

	public RecVisitRecord(int dbid) {
		this.dbid = dbid;
	}

	public RecVisitRecord(int dbid, Integer gzUserId, Date startTime, Date leaveTime, Integer timeLong, String ip,
			String areaStr, String city, String provice) {
		this.dbid = dbid;
		this.gzUserId = gzUserId;
		this.startTime = startTime;
		this.leaveTime = leaveTime;
		this.timeLong = timeLong;
		this.ip = ip;
		this.areaStr = areaStr;
		this.city = city;
		this.provice = provice;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getGzUserId() {
		return this.gzUserId;
	}

	public void setGzUserId(Integer gzUserId) {
		this.gzUserId = gzUserId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getLeaveTime() {
		return this.leaveTime;
	}

	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}

	public Integer getTimeLong() {
		return this.timeLong;
	}

	public void setTimeLong(Integer timeLong) {
		this.timeLong = timeLong;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getAreaStr() {
		return this.areaStr;
	}

	public void setAreaStr(String areaStr) {
		this.areaStr = areaStr;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvice() {
		return this.provice;
	}

	public void setProvice(String provice) {
		this.provice = provice;
	}

	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}
	

}
