package com.ystech.weixin.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2015-9-9 17:17:16 by Hibernate Tools 4.0.0

/**
 * WeixinWechatnewstemplate generated by hbm2java
 */
public class WechatNewsTemplate implements java.io.Serializable {

	private Integer dbid;
	private String addtime;
	private String title;
	private Integer type;
	private Integer accountId;
	private String mediaId;
	private Set wechatNewsitems = new HashSet(0);
	public WechatNewsTemplate() {
	}

	public WechatNewsTemplate(String addtime, String title, Integer type,
			Integer accountId, String mediaId) {
		this.addtime = addtime;
		this.title = title;
		this.type = type;
		this.accountId = accountId;
		this.mediaId = mediaId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getAddtime() {
		return this.addtime;
	}

	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	public Set getWechatNewsitems() {
		return wechatNewsitems;
	}

	public void setWechatNewsitems(Set wechatNewsitems) {
		this.wechatNewsitems = wechatNewsitems;
	}

}
