package com.ystech.weixin.model;

import java.util.Date;

// Generated 2016-10-15 16:44:26 by Hibernate Tools 4.0.0

/**
 * Customerinfrom generated by hbm2java
 * 功能描述：线索来源
 */
public class WechatIndustry implements java.io.Serializable {

	private Integer dbid;
	//来源名称
	private String name;
	//备注
	private String note;
	//排序
	private Integer num;
	//1、主业；2、副业
	private Integer type;
	//代码
	private String code;
	//是否父节点
	private WechatIndustry parent;
	//等级
	private Date createDate;
	private Date modifyDate;

	public WechatIndustry() {
	}

	public WechatIndustry(String name, String note, Integer num,
			Integer parentId, Integer levelNum) {
		this.name = name;
		this.note = note;
		this.num = num;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}


	public WechatIndustry getParent() {
		return parent;
	}

	public void setParent(WechatIndustry parent) {
		this.parent = parent;
	}


	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
