package com.ystech.weixin.model;

// Generated 2015-9-11 15:00:31 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WeixinWehcatmedia generated by hbm2java
 */
public class WechatMedia implements java.io.Serializable {
	public static Integer MEDIAIMAGE=1;
	public static Integer MEDIACONTENT=1;
	private Integer dbid;
	private String errcode;
	private String errmsg;
	private String type;
	private String thumbUrl;
	private String thumbWechatUrl;
	private String mediaId;
	private Date uploadDate;
	//多媒体 类型 1、永久素材、2、系统具体内容图文
	private Integer mediaType;
	private String name;
	private Integer weixinAccountId;
	public WechatMedia() {
	}

	public WechatMedia(String errcode, String errmsg, String type,
			String thumbUrl, String thumbWechatUrl, String mediaId,
			Date uploadDate) {
		this.errcode = errcode;
		this.errmsg = errmsg;
		this.type = type;
		this.thumbUrl = thumbUrl;
		this.thumbWechatUrl = thumbWechatUrl;
		this.mediaId = mediaId;
		this.uploadDate = uploadDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getErrcode() {
		return this.errcode;
	}

	public void setErrcode(String errcode) {
		this.errcode = errcode;
	}

	public String getErrmsg() {
		return this.errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getThumbUrl() {
		return this.thumbUrl;
	}

	public void setThumbUrl(String thumbUrl) {
		this.thumbUrl = thumbUrl;
	}

	public String getThumbWechatUrl() {
		return this.thumbWechatUrl;
	}

	public void setThumbWechatUrl(String thumbWechatUrl) {
		this.thumbWechatUrl = thumbWechatUrl;
	}

	public String getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public Integer getMediaType() {
		return mediaType;
	}

	public void setMediaType(Integer mediaType) {
		this.mediaType = mediaType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getWeixinAccountId() {
		return weixinAccountId;
	}

	public void setWeixinAccountId(Integer weixinAccountId) {
		this.weixinAccountId = weixinAccountId;
	}
	
}
