package com.ystech.weixin.model;
// Generated 2017-1-18 21:01:52 by Hibernate Tools 4.0.0.Final

/**
 * WeixinMenuentitygroupmatchrule generated by hbm2java
 */
public class WeixinMenuentityGroupMatchRule implements java.io.Serializable {

	private Integer dbid;
	//分组ID
	private String group_id;
	//性别
	private String sex;
	//手机客户端
	private String client_platform_type;
	//国家
	private String country;
	//省
	private String province;
	//城市
	private String city;
	//语言
	private String language;
	
	private WeixinMenuentityGroup weixinMenuentityGroup;
	
	public String getGroup_id() {
		return group_id;
	}

	public void setGroup_id(String group_id) {
		this.group_id = group_id;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getClient_platform_type() {
		return client_platform_type;
	}

	public void setClient_platform_type(String client_platform_type) {
		this.client_platform_type = client_platform_type;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public WeixinMenuentityGroup getWeixinMenuentityGroup() {
		return weixinMenuentityGroup;
	}

	public void setWeixinMenuentityGroup(WeixinMenuentityGroup weixinMenuentityGroup) {
		this.weixinMenuentityGroup = weixinMenuentityGroup;
	}

}
