package com.ystech.weixin.model;

// Generated 2015-6-7 21:57:03 by Hibernate Tools 4.0.0

/**
 * WeixinExpandconfig generated by hbm2java
 */
public class WeixinExpandconfig implements java.io.Serializable {

	private String id;
	private String accountid;
	private String classname;
	private String content;
	private String keyword;
	private String name;

	public WeixinExpandconfig() {
	}

	public WeixinExpandconfig(String id, String classname, String keyword) {
		this.id = id;
		this.classname = classname;
		this.keyword = keyword;
	}

	public WeixinExpandconfig(String id, String accountid, String classname,
			String content, String keyword, String name) {
		this.id = id;
		this.accountid = accountid;
		this.classname = classname;
		this.content = content;
		this.keyword = keyword;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
