package com.ystech.weixin.model;

import java.util.Date;


// Generated 2015-6-7 21:36:04 by Hibernate Tools 4.0.0

/**
 * WeixinAutoresponse generated by hbm2java
 */
public class WeixinKeyWord implements java.io.Serializable {

	private Integer dbid;
	private String keyword;//关键词
	//匹配类型 1、全匹配；2、模糊匹配
	private Integer matchingType;
	private WeixinKeyWordRole weixinKeyWordRole;
	private Date createDate;
	private Date modifyDate;
	
	public WeixinKeyWord() {
	}

	public WeixinKeyWord(String id) {
	}

	public WeixinKeyWord(String id, String addtime, String keyword,
			String msgtype, String rescontent, String templatename,
			String accountid) {
		this.keyword = keyword;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Integer getMatchingType() {
		return matchingType;
	}

	public void setMatchingType(Integer matchingType) {
		this.matchingType = matchingType;
	}

	public WeixinKeyWordRole getWeixinKeyWordRole() {
		return weixinKeyWordRole;
	}

	public void setWeixinKeyWordRole(WeixinKeyWordRole weixinKeyWordRole) {
		this.weixinKeyWordRole = weixinKeyWordRole;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	
}
