package com.ystech.weixin.model;

import java.util.Date;

// Generated 2015-6-7 21:36:04 by Hibernate Tools 4.0.0

/**
 * WeixinAutoresponse generated by hbm2java
 */
public class WeixinKeyAutoresponse implements java.io.Serializable {

	private Integer dbid;
	private String msgtype;//消息类型(文本、图文、图片）
	private Integer templateId;//
	private String templatename;// 关联模板名称
	private WeixinKeyWordRole weixinKeyWordRole;
	private Date createDate;
	private Date modifyDate;
	private String content;
	public WeixinKeyAutoresponse() {
	}

	public WeixinKeyAutoresponse(String id) {
	}

	public WeixinKeyAutoresponse(String id, String addtime, String keyword,
			String msgtype, String rescontent, String templatename,
			String accountid) {
		this.msgtype = msgtype;
		this.templatename = templatename;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}



	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}


	public Integer getTemplateId() {
		return templateId;
	}

	public void setTemplateId(Integer templateId) {
		this.templateId = templateId;
	}

	public String getTemplatename() {
		return this.templatename;
	}

	public void setTemplatename(String templatename) {
		this.templatename = templatename;
	}

	public WeixinKeyWordRole getWeixinKeyWordRole() {
		return weixinKeyWordRole;
	}

	public void setWeixinKeyWordRole(WeixinKeyWordRole weixinKeyWordRole) {
		this.weixinKeyWordRole = weixinKeyWordRole;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	
}
