package com.ystech.weixin.model;

// Generated 2015-6-7 9:29:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WeixinAccount generated by hbm2java
 */
public class WeixinAccount implements java.io.Serializable {
	/**主键*/
	private Integer dbid;
	/**公众帐号名称*/
	private java.lang.String accountname;
	/**公众帐号TOKEN*/
	private java.lang.String accounttoken;
	/**公众微信号*/
	private java.lang.String accountnumber;
	/**公众原始ID*/
	private java.lang.String weixinAccountid;
	/**公众号类型*/
	private java.lang.String accounttype;
	/**电子邮箱*/
	private java.lang.String accountemail;
	/**公众帐号描述*/
	private java.lang.String accountdesc;
	/**公众帐号APPID*/
	private java.lang.String accountappid;
	/**公众帐号APPSECRET*/
	private java.lang.String accountappsecret;
	/**ACCESS_TOKEN*/
	private java.lang.String accountaccesstoken;
	/**TOKEN获取时间*/
	private java.util.Date addtoekntime;
	/**所属系统用户ID 商家管理员ID**/
	private Integer userDbid;
	private String code;
	//企业ID
	private Integer enterpriseId;

	public WeixinAccount() {
	}

	public WeixinAccount(String id) {
	}

	public WeixinAccount(String id, String accountname, String accounttoken,
			String accountnumber, String accounttype, String accountemail,
			String accountdesc, String accountaccesstoken, String accountappid,
			String accountappsecret, Date addtoekntime, String username,
			String weixinAccountid) {
		this.accountname = accountname;
		this.accounttoken = accounttoken;
		this.accountnumber = accountnumber;
		this.accounttype = accounttype;
		this.accountemail = accountemail;
		this.accountdesc = accountdesc;
		this.accountaccesstoken = accountaccesstoken;
		this.accountappid = accountappid;
		this.accountappsecret = accountappsecret;
		this.addtoekntime = addtoekntime;
		this.weixinAccountid = weixinAccountid;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	public String getAccounttoken() {
		return this.accounttoken;
	}

	public void setAccounttoken(String accounttoken) {
		this.accounttoken = accounttoken;
	}

	public String getAccountnumber() {
		return this.accountnumber;
	}

	public void setAccountnumber(String accountnumber) {
		this.accountnumber = accountnumber;
	}

	public String getAccounttype() {
		return this.accounttype;
	}

	public void setAccounttype(String accounttype) {
		this.accounttype = accounttype;
	}

	public String getAccountemail() {
		return this.accountemail;
	}

	public void setAccountemail(String accountemail) {
		this.accountemail = accountemail;
	}

	public String getAccountdesc() {
		return this.accountdesc;
	}

	public void setAccountdesc(String accountdesc) {
		this.accountdesc = accountdesc;
	}

	public String getAccountaccesstoken() {
		return this.accountaccesstoken;
	}

	public void setAccountaccesstoken(String accountaccesstoken) {
		this.accountaccesstoken = accountaccesstoken;
	}

	public String getAccountappid() {
		return this.accountappid;
	}

	public void setAccountappid(String accountappid) {
		this.accountappid = accountappid;
	}

	public String getAccountappsecret() {
		return this.accountappsecret;
	}

	public void setAccountappsecret(String accountappsecret) {
		this.accountappsecret = accountappsecret;
	}

	public Date getAddtoekntime() {
		return this.addtoekntime;
	}

	public void setAddtoekntime(Date addtoekntime) {
		this.addtoekntime = addtoekntime;
	}



	public Integer getUserDbid() {
		return userDbid;
	}

	public void setUserDbid(Integer userDbid) {
		this.userDbid = userDbid;
	}

	public String getWeixinAccountid() {
		return this.weixinAccountid;
	}

	public void setWeixinAccountid(String weixinAccountid) {
		this.weixinAccountid = weixinAccountid;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	
}
