package com.ystech.weixin.model;

// Generated 2015-6-7 21:57:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * WeixinNewstemplate generated by hbm2java
 */
public class WeixinNewstemplate implements java.io.Serializable {

	private Integer dbid;
	private String addtime;//添加时间
	private String templatename;//名称
	private String type;//类型
	private String accountid;//账号ID
	private Set weixinNewsitems = new HashSet(0);

	public WeixinNewstemplate() {
	}

	public WeixinNewstemplate(String id) {
	}

	public WeixinNewstemplate(String id, String addtime, String tempatename,
			String type, String accountid, Set weixinNewsitems) {
		this.addtime = addtime;
		this.type = type;
		this.accountid = accountid;
		this.weixinNewsitems = weixinNewsitems;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getAddtime() {
		return this.addtime;
	}

	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}


	public String getTemplatename() {
		return templatename;
	}

	public void setTemplatename(String templatename) {
		this.templatename = templatename;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	public Set getWeixinNewsitems() {
		return this.weixinNewsitems;
	}

	public void setWeixinNewsitems(Set weixinNewsitems) {
		this.weixinNewsitems = weixinNewsitems;
	}

}
