package com.ystech.weixin.model;
// Generated 2016-11-20 21:48:25 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.Set;


/**
 * WeixinKeywordrole generated by hbm2java
 */
public class WeixinKeyWordRole implements java.io.Serializable {
	public static Integer TYPESUBSC=3; 

	private Integer dbid;
	//规程名称
	private String name;
	private Date createDate;
	private Date modifyDate;
	//类型：1、系统默认；2、参数二维码;3、关注自动回复
	private Integer type;
	//商家ID
	private Integer accountid;
	Set<WeixinKeyWord> weixinKeyWords;
	
	Set<WeixinKeyAutoresponse> weixinKeyAutoresponses;
	
	public WeixinKeyWordRole() {
	}

	public WeixinKeyWordRole(String name, Date createDate, Date modifyDate, Integer type, Integer accountid,
			Integer spreadDetailId) {
		this.name = name;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.type = type;
		this.accountid = accountid;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getAccountid() {
		return this.accountid;
	}

	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}



	public Set<WeixinKeyWord> getWeixinKeyWords() {
		return weixinKeyWords;
	}

	public void setWeixinKeyWords(Set<WeixinKeyWord> weixinKeyWords) {
		this.weixinKeyWords = weixinKeyWords;
	}

	public Set<WeixinKeyAutoresponse> getWeixinKeyAutoresponses() {
		return weixinKeyAutoresponses;
	}

	public void setWeixinKeyAutoresponses(Set<WeixinKeyAutoresponse> weixinKeyAutoresponses) {
		this.weixinKeyAutoresponses = weixinKeyAutoresponses;
	}
	
}
