package com.ystech.agent.model;

import java.util.Date;

// Generated 2017-7-6 11:56:43 by Hibernate Tools 4.0.0

/**
 * AgentAgentset generated by hbm2java
 * @author shusanzhan
 * @date 2017-07-06
 */
public class AgentSet implements java.io.Serializable {
	//启用状态
	public static final int START=1;
	//停用状态
	public static final int STOP=2;
	private Integer dbid;
	//经纪人注册是否开启推荐权限 默认开启
	private Integer authAgentStatus;
	//是否开启推荐经纪人人员奖励
	private Integer regParentRewardStatus;
	//推荐经纪人人员奖励金额
	private Integer regParentRewardNum;
	//是否开启经纪人注册奖励
	private Integer regRewardStatus;
	//经纪人注册奖励金额
	private Integer regRewardNum;
	//是否开启经纪人推荐客户成交后奖励
	private Integer agentRewardStatus;
	//经纪人推荐客户成交后奖励金额
	private Integer agentRewardNum;
	
	//是否开启经纪人推荐客户成交后,对上级奖励
	private Integer agentRewardParentStatus;
	//经纪人推荐客户成交后对上级奖励金额
	private Integer agentRewardParentNum;
	//奖励模式：1、固定奖励；2、梯度奖励
	private Integer agentRewardModel;
	//集团版 企业ID
	private Integer enterpriseId;
	private Date createTime;
	private Date modifyTime;
	private Integer spreadId;
	public AgentSet() {
	}

	public AgentSet(Integer authAgentStatus, Integer parentRewardStatus,
			Integer parentRewardNum, Integer regRewardStatus,
			Integer regRewardNum, Integer agentRewardStatus,
			Integer agentRewardNum) {
		this.authAgentStatus = authAgentStatus;
		this.regRewardStatus = regRewardStatus;
		this.regRewardNum = regRewardNum;
		this.agentRewardStatus = agentRewardStatus;
		this.agentRewardNum = agentRewardNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getAuthAgentStatus() {
		return this.authAgentStatus;
	}

	public void setAuthAgentStatus(Integer authAgentStatus) {
		this.authAgentStatus = authAgentStatus;
	}


	public Integer getRegRewardStatus() {
		return this.regRewardStatus;
	}

	public void setRegRewardStatus(Integer regRewardStatus) {
		this.regRewardStatus = regRewardStatus;
	}

	public Integer getRegRewardNum() {
		return this.regRewardNum;
	}

	public void setRegRewardNum(Integer regRewardNum) {
		this.regRewardNum = regRewardNum;
	}

	public Integer getAgentRewardStatus() {
		return this.agentRewardStatus;
	}

	public void setAgentRewardStatus(Integer agentRewardStatus) {
		this.agentRewardStatus = agentRewardStatus;
	}

	public Integer getAgentRewardNum() {
		return this.agentRewardNum;
	}

	public void setAgentRewardNum(Integer agentRewardNum) {
		this.agentRewardNum = agentRewardNum;
	}
	
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
	public Integer getAgentRewardParentStatus() {
		return agentRewardParentStatus;
	}

	public void setAgentRewardParentStatus(Integer agentRewardParentStatus) {
		this.agentRewardParentStatus = agentRewardParentStatus;
	}

	public Integer getAgentRewardParentNum() {
		return agentRewardParentNum;
	}

	public void setAgentRewardParentNum(Integer agentRewardParentNum) {
		this.agentRewardParentNum = agentRewardParentNum;
	}

	public Integer getRegParentRewardStatus() {
		return regParentRewardStatus;
	}

	public void setRegParentRewardStatus(Integer regParentRewardStatus) {
		this.regParentRewardStatus = regParentRewardStatus;
	}

	public Integer getRegParentRewardNum() {
		return regParentRewardNum;
	}

	public void setRegParentRewardNum(Integer regParentRewardNum) {
		this.regParentRewardNum = regParentRewardNum;
	}

	@Override
	public String toString() {
		return "AgentSet [dbid=" + dbid + ", authAgentStatus="
				+ authAgentStatus + ", parentRewardStatus="
				+ ", regRewardStatus=" + regRewardStatus + ", regRewardNum="
				+ regRewardNum + ", agentRewardStatus=" + agentRewardStatus
				+ ", agentRewardNum=" + agentRewardNum
				+ ", agentRewardParentStatus=" + agentRewardParentStatus
				+ ", agentRewardParentNum=" + agentRewardParentNum
				+ ", enterpriseId=" + enterpriseId + ", createTime="
				+ createTime + ", modifyTime=" + modifyTime + "]";
	}


	public Integer getSpreadId() {
		return spreadId;
	}

	public void setSpreadId(Integer spreadId) {
		this.spreadId = spreadId;
	}

	public Integer getAgentRewardModel() {
		return agentRewardModel;
	}

	public void setAgentRewardModel(Integer agentRewardModel) {
		this.agentRewardModel = agentRewardModel;
	}
	


}
