package com.ystech.agent.model;

// Generated 2016-3-22 23:04:43 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AgentAgentcompany generated by hbm2java
 */
public class AgentCompany implements java.io.Serializable {

	private Integer dbid;
	private Integer companyId;
	private Agent agent;
	private Date createDate;
	private Date modifyDate;
	//成功推荐人数
	private Integer successNum;
	//推荐人数
	private Integer agentNum;

	public AgentCompany() {
	}

	public AgentCompany(Integer companyId, Integer agentId,
			Date createDate, Date modifyDate) {
		this.companyId = companyId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Agent getAgent() {
		return agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getSuccessNum() {
		return successNum;
	}

	public void setSuccessNum(Integer successNum) {
		this.successNum = successNum;
	}

	public Integer getAgentNum() {
		return agentNum;
	}

	public void setAgentNum(Integer agentNum) {
		this.agentNum = agentNum;
	}
	

}
