package com.ystech.agent.model;

// Generated 2017-8-9 8:45:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AgentAgenttype generated by hbm2java
 */
public class AgentType implements java.io.Serializable {

	private Integer dbid;
	//经纪人类型名称
	private String name;
	//备注
	private String note;
	//类型
	private Integer type;
	private Integer enterpriseId;
	//排序
	private Integer orderNum;
	//创建时间
	private Date createTime;
	//修改时间
	private Date modifyTime;

	public AgentType() {
	}

	public AgentType(String name, String note, Integer type,
			Integer orderNum, Date createTime, Date modifyTime) {
		this.name = name;
		this.note = note;
		this.type = type;
		this.orderNum = orderNum;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}
	
}
