package com.ystech.agent.model;

import java.util.Date;

import com.ystech.weixin.model.WeixinKeyAutoresponse;


// Generated 2016-7-31 10:37:29 by Hibernate Tools 4.0.0

/**
 * AgentMesg generated by hbm2java
 */
public class AgentMesg implements java.io.Serializable {
	public static Integer COMM=1;
	public static Integer SUCC=2;
	public static Integer FAIL=3;
	private Integer dbid;
	//内容
	private String mesg;
	//用户Id
	private Integer userId;
	//真实姓名
	private String realName;
	//
	private String openId;
	//发送状态
	private Integer sendStatus;
	//发送次数
	private Integer sendNum;
	private Date createDate;
	private Date modifyDate;
	private Integer enterpriseId;
	//news text
	private String msgType;
	private WeixinKeyAutoresponse weixinKeyAutoresponse;
	public AgentMesg() {
	}

	public AgentMesg(String mesg, Integer userId, String openId,
			Integer sendStatus, Integer sendNum) {
		this.mesg = mesg;
		this.userId = userId;
		this.openId = openId;
		this.sendStatus = sendStatus;
		this.sendNum = sendNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getMesg() {
		return this.mesg;
	}

	public void setMesg(String mesg) {
		this.mesg = mesg;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public Integer getSendStatus() {
		return this.sendStatus;
	}

	public void setSendStatus(Integer sendStatus) {
		this.sendStatus = sendStatus;
	}

	public Integer getSendNum() {
		return this.sendNum;
	}

	public void setSendNum(Integer sendNum) {
		this.sendNum = sendNum;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getMsgType() {
		return msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public WeixinKeyAutoresponse getWeixinKeyAutoresponse() {
		return weixinKeyAutoresponse;
	}

	public void setWeixinKeyAutoresponse(WeixinKeyAutoresponse weixinKeyAutoresponse) {
		this.weixinKeyAutoresponse = weixinKeyAutoresponse;
	}

	
}
