package com.ystech.agent.model;

// Generated 2016-4-6 11:11:00 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Customerflowreason generated by hbm2java
 */
public class FlowReason implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String note;
	private Date createDate;
	private Date modifyDate;
	private Integer orderNum;

	public FlowReason() {
	}

	public FlowReason(String name, String note, Date createDate,
			Date modifyDate, Integer orderNum) {
		this.name = name;
		this.note = note;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.orderNum = orderNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

}
