package com.ystech.agent.model;

// Generated 2016-2-29 21:39:09 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.mem.model.Member;
import com.ystech.xwqr.model.sys.Area;
import com.ystech.xwqr.model.sys.User;
import com.ystech.xwqr.set.model.Brand;
import com.ystech.xwqr.set.model.CarModel;
import com.ystech.xwqr.set.model.CarSeriy;

/**
 * AgentRecommendcustomerf generated by hbm2java
 */
public class RecommendCustomer implements java.io.Serializable {
	//审批状态1、等待审批；2、已经分配客户；3、客户无效
	public  static Integer APPROVALWAITING=1;
	public  static Integer APPROVALED=2;
	public  static Integer APPROVALINVALID=3;
	//客户登记状态
	public  static Integer CUSTOMERSTATUSCOMM=1;
	public  static Integer CUSTOMERSTATUSYEAS=2;
	//分配状态
	public static Integer DISTWATING=1;
	public static Integer DISTED=2;
	//交易状态1、交易中；2、交易成功；3、交易失败
	public static Integer TRADECOMM=1;
	public static Integer TRADESUCCESS=2;
	public static Integer TRADEFAIL=3;
	
	//交易状态1、待发送；2、已发送
	public static Integer REWARD_COMM=1;
	public static Integer REWARD_SENDED=2;
	
	private int dbid;
	//推荐人
	private Member member;
	//客户姓名
	private String name;
	//客户姓名
	private String sex;
	private String openId;
	//联系电话
	private String mobilePhone;
	//购车预算
	private String budgetMoney;
	//推荐人
	private Date recommendDate;
	//推荐人姓名
	private String agentName;
	//推荐人电话
	private String agentPhone;
	//省
	private String province;
	//城市
	private String city;
	//区域
	private String areaStr;
	//区域
	private Area area;
	
	//品牌
	private Brand brand;
	//车系
	private CarSeriy carSeriy;
	//车型
	private CarModel carModel;
	//
	private String carModelName;
	//
	private Integer carriageType;
	
	//交易情况:待分配；已经
	private Integer tradeStatus;
	//分配状态：1、等待分配；2、已经分配
	private Integer distStatus;
	//审批状态1、等待审批；2、已经分配客户；3、客户无效
	private Integer approvalStatus;
	//商家Id
	private Integer shopId;
	//审批时间
	private Date approvalDate;
	//审批人
	private String approvalUser;
	//创建时间
	private Date createDate;
	//修改时间
	private Date modifyDate;
	//经销商名称
	private String compnayName;
	//分配跟进销售顾问
	private User saler;
	//分配时间
	private Date distDate;
	//分配操作人
	private String distUser;
	
	//是否转为登记客户;1、为正常；2、为转为登记客户
	private Integer customerStatus;
	//区域奖励金额
	private Float rewardMoney;
	//区域赠送积分
	private Float point;
	
	//客户无效原因
	private FlowReason flowReason;
	
	//客户无效备注
	private String flowNote;
	private Integer enterpriseId;
	
	private Integer rewardStatus;
	private Date rewardTime;
	private String rewardNote;
	
	public RecommendCustomer() {
	}

	public RecommendCustomer(int dbid) {
		this.dbid = dbid;
	}

	public RecommendCustomer(int dbid, 
			String name, String sex, String mobilePhone, Date recommendDate,
			String agentName, String agentPhone, String province, String city,
			String area, Integer brandId, Integer carSeriyId,
			Integer carModelId, Integer carriageType, Integer tradeStatus,
			Integer approvalStatus, Integer shopId, Date approvalDate,
			String approvalUser, Date createDate, Date modifyDate) {
		this.dbid = dbid;
		this.name = name;
		this.sex = sex;
		this.mobilePhone = mobilePhone;
		this.recommendDate = recommendDate;
		this.agentName = agentName;
		this.agentPhone = agentPhone;
		this.province = province;
		this.city = city;
		this.carriageType = carriageType;
		this.tradeStatus = tradeStatus;
		this.approvalStatus = approvalStatus;
		this.shopId = shopId;
		this.approvalDate = approvalDate;
		this.approvalUser = approvalUser;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public int getDbid() {
		return this.dbid;
	}

	public void setDbid(int dbid) {
		this.dbid = dbid;
	}



	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public Date getRecommendDate() {
		return this.recommendDate;
	}

	public void setRecommendDate(Date recommendDate) {
		this.recommendDate = recommendDate;
	}

	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	public String getAgentPhone() {
		return this.agentPhone;
	}

	public void setAgentPhone(String agentPhone) {
		this.agentPhone = agentPhone;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getAreaStr() {
		return areaStr;
	}

	public void setAreaStr(String areaStr) {
		this.areaStr = areaStr;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public CarSeriy getCarSeriy() {
		return carSeriy;
	}

	public void setCarSeriy(CarSeriy carSeriy) {
		this.carSeriy = carSeriy;
	}

	public CarModel getCarModel() {
		return carModel;
	}

	public void setCarModel(CarModel carModel) {
		this.carModel = carModel;
	}

	public Integer getCarriageType() {
		return this.carriageType;
	}

	public void setCarriageType(Integer carriageType) {
		this.carriageType = carriageType;
	}

	public Integer getTradeStatus() {
		return this.tradeStatus;
	}

	public void setTradeStatus(Integer tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

	public Integer getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Integer approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public String getApprovalUser() {
		return this.approvalUser;
	}

	public void setApprovalUser(String approvalUser) {
		this.approvalUser = approvalUser;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}


	public User getSaler() {
		return saler;
	}

	public void setSaler(User saler) {
		this.saler = saler;
	}

	public Date getDistDate() {
		return distDate;
	}

	public void setDistDate(Date distDate) {
		this.distDate = distDate;
	}

	public String getDistUser() {
		return distUser;
	}

	public void setDistUser(String distUser) {
		this.distUser = distUser;
	}

	public Integer getDistStatus() {
		return distStatus;
	}

	public void setDistStatus(Integer distStatus) {
		this.distStatus = distStatus;
	}

	public String getCarModelName() {
		return carModelName;
	}

	public void setCarModelName(String carModelName) {
		this.carModelName = carModelName;
	}

	public Integer getCustomerStatus() {
		return customerStatus;
	}

	public void setCustomerStatus(Integer customerStatus) {
		this.customerStatus = customerStatus;
	}

	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public Float getRewardMoney() {
		return rewardMoney;
	}

	public void setRewardMoney(Float rewardMoney) {
		this.rewardMoney = rewardMoney;
	}

	public Float getPoint() {
		return point;
	}

	public void setPoint(Float point) {
		this.point = point;
	}

	public FlowReason getFlowReason() {
		return flowReason;
	}

	public void setFlowReason(FlowReason flowReason) {
		this.flowReason = flowReason;
	}

	public String getFlowNote() {
		return flowNote;
	}

	public void setFlowNote(String flowNote) {
		this.flowNote = flowNote;
	}

	public String getCompnayName() {
		return compnayName;
	}

	public void setCompnayName(String compnayName) {
		this.compnayName = compnayName;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getBudgetMoney() {
		return budgetMoney;
	}

	public void setBudgetMoney(String budgetMoney) {
		this.budgetMoney = budgetMoney;
	}

	public Integer getRewardStatus() {
		return rewardStatus;
	}

	public void setRewardStatus(Integer rewardStatus) {
		this.rewardStatus = rewardStatus;
	}

	public Date getRewardTime() {
		return rewardTime;
	}

	public void setRewardTime(Date rewardTime) {
		this.rewardTime = rewardTime;
	}

	public String getRewardNote() {
		return rewardNote;
	}

	public void setRewardNote(String rewardNote) {
		this.rewardNote = rewardNote;
	}
	
	
}
