package com.ystech.agent.model;

import com.ystech.xwqr.model.sys.User;

// Generated 2016-7-31 0:04:00 by Hibernate Tools 4.0.0

/**
 * AgentWechatrecvier generated by hbm2java
 */
public class WechatRecvier implements java.io.Serializable {

	private Integer dbid;
	private User user;
	private String openId;

	public WechatRecvier() {
	}

	public WechatRecvier(Integer userId, String openId) {
		this.openId = openId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

}
