package com.ystech.mem.model;

// Generated 2014-4-10 18:03:39 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coupon generated by hbm2java
 */
public class Coupon implements java.io.Serializable {
	
	private Integer dbid;
	private String name;
	private Integer type;
	private String image;
	//消费满
	private Float conditions;
	private float moneyOrRabatt;
	private Integer ausgabeCount;
	private Integer userReceiveNum;
	private Integer receivedNum;
	private Date startTime;
	private Date stopTime;
	private String description;
	private boolean isExchange;
	private Integer exchangeNum;
	private boolean enabled;
	private Date createTime;
	private Date modifyTime;
	private String reason;
	private Set couponcodes = new HashSet(0);
	private boolean isReceive=false;
	private boolean showHiden;
	//分公司是ID
	private Integer enterpriseId;
	public Coupon() {
	}

	public Coupon(String name, float moneyOrRabatt, Date startTime,
			Date stopTime, boolean isExchange, boolean enabled) {
		this.name = name;
		this.moneyOrRabatt = moneyOrRabatt;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.isExchange = isExchange;
		this.enabled = enabled;
	}

	public Coupon(String name, Integer type, byte[] image, Float conditions,
			float moneyOrRabatt, Integer ausgabeCount, Integer userReceiveNum,
			Integer receivedNum, Date startTime, Date stopTime,
			String description, boolean isExchange, Integer exchangeNum,
			boolean enabled, Date createTime, Date modifyTime, Integer bussiId,
			Set couponcodes) {
		this.name = name;
		this.type = type;
		this.conditions = conditions;
		this.moneyOrRabatt = moneyOrRabatt;
		this.ausgabeCount = ausgabeCount;
		this.userReceiveNum = userReceiveNum;
		this.receivedNum = receivedNum;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.description = description;
		this.isExchange = isExchange;
		this.exchangeNum = exchangeNum;
		this.enabled = enabled;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.couponcodes = couponcodes;
	}
	
	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Float getConditions() {
		return this.conditions;
	}

	public void setConditions(Float conditions) {
		this.conditions = conditions;
	}

	public float getMoneyOrRabatt() {
		return this.moneyOrRabatt;
	}

	public void setMoneyOrRabatt(float moneyOrRabatt) {
		this.moneyOrRabatt = moneyOrRabatt;
	}

	public Integer getAusgabeCount() {
		return this.ausgabeCount;
	}

	public void setAusgabeCount(Integer ausgabeCount) {
		this.ausgabeCount = ausgabeCount;
	}

	public Integer getUserReceiveNum() {
		return this.userReceiveNum;
	}

	public void setUserReceiveNum(Integer userReceiveNum) {
		this.userReceiveNum = userReceiveNum;
	}

	public Integer getReceivedNum() {
		return this.receivedNum;
	}

	public void setReceivedNum(Integer receivedNum) {
		this.receivedNum = receivedNum;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getStopTime() {
		return this.stopTime;
	}

	public void setStopTime(Date stopTime) {
		this.stopTime = stopTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isIsExchange() {
		return this.isExchange;
	}

	public void setIsExchange(boolean isExchange) {
		this.isExchange = isExchange;
	}

	public Integer getExchangeNum() {
		return this.exchangeNum;
	}

	public void setExchangeNum(Integer exchangeNum) {
		this.exchangeNum = exchangeNum;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}


	public Set getCouponcodes() {
		return this.couponcodes;
	}

	public void setCouponcodes(Set couponcodes) {
		this.couponcodes = couponcodes;
	}

	public boolean isExchange() {
		return isExchange;
	}

	public void setExchange(boolean isExchange) {
		this.isExchange = isExchange;
	}

	public boolean isReceive() {
		return isReceive;
	}

	public void setReceive(boolean isReceive) {
		this.isReceive = isReceive;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getReason() {
		return reason;
	}

	public boolean getShowHiden() {
		return showHiden;
	}

	public void setShowHiden(boolean showHiden) {
		this.showHiden = showHiden;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}


	
	
}
