package com.ystech.mem.model;

// Generated 2014-4-10 18:03:39 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Couponcode generated by hbm2java
 */
public class CouponCode implements java.io.Serializable {

	private int dbid;
	private Coupon coupon;
	private Member member;
	private Date createTime;
	private Date modifyTime;
	private String code;
	
	public CouponCode() {
	}

	public CouponCode(int dbid) {
		this.dbid = dbid;
	}

	public CouponCode(int dbid, Coupon coupon, Member member,
			Date createTime, Date modifyTime, String code, Boolean isUsed,
			Date usedDate) {
		this.dbid = dbid;
		this.coupon = coupon;
		this.member = member;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.code = code;
	}

	public int getDbid() {
		return this.dbid;
	}

	public void setDbid(int dbid) {
		this.dbid = dbid;
	}

	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}


	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
