package com.ystech.mem.model;

// Generated 2014-4-10 18:03:39 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.Set;

import com.ystech.xwqr.model.sys.Department;

/**会员定向券，会员领用券信息
 * Coupon generated by hbm2java
 */
public class CouponMember implements java.io.Serializable {
	public static final Integer NORMALCOUPON=1;
	public static final Integer DIRECTCOUPON=2;
	private Integer dbid;
	//优惠券类型 是定向券、普通券
	private Integer bigType;
	//优惠券名称
	private String name;
	//优惠券类型 代金券、折扣券
	private Integer type;
	//图片
	private String image;
	//折扣率
	private float moneyOrRabatt;
	//优惠券有效期 开始时间
	private Date startTime;
	//优惠券有效期 结束时间
	private Date stopTime;
	//优惠券描述
	private String description;
	//是否启用
	private boolean enabled;
	//创建时间
	private Date createTime;
	//修改时间
	private Date modifyTime;
	//sn码
	private String code;
	//会员
	private Member member;
	//是否使用
	private Boolean isUsed;
	//使用状态
	private Date usedDate;
	//创建人Id
	private Integer creatorId;
	//优惠码的创建人
	private String creatorName;
	//使用人ID
	private Integer usedPersonId;
	//优惠码的使用人
	private String usedPersonName;
	private String reason;
	private CouponMemberTemplate couponMemberTemplate;
	private boolean showHiden;
	private Integer enterpriseId;
	//优惠券业务类型：1、销售劵；2、售后发放劵；3、保险发放劵；
	private Integer bussiType;
	private Department sendDep;
	private String sendDepName;
	public CouponMember() {
	}
	public CouponMember(String name, float moneyOrRabatt, Date startTime,
			Date stopTime, boolean isExchange, boolean enabled) {
		this.name = name;
		this.moneyOrRabatt = moneyOrRabatt;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.enabled = enabled;
	}

	public CouponMember(String name, Integer type, byte[] image, Float conditions,
			float moneyOrRabatt, Integer ausgabeCount, Integer userReceiveNum,
			Integer receivedNum, Date startTime, Date stopTime,
			String description, boolean isExchange, Integer exchangeNum,
			boolean enabled, Date createTime, Date modifyTime, Integer bussiId,
			Set couponcodes) {
		this.name = name;
		this.type = type;
		this.moneyOrRabatt = moneyOrRabatt;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.description = description;
		this.enabled = enabled;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public Integer getDbid() {
		return this.dbid;
	}
	

	public Integer getBigType() {
		return bigType;
	}
	public void setBigType(Integer bigType) {
		this.bigType = bigType;
	}
	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}


	public float getMoneyOrRabatt() {
		return this.moneyOrRabatt;
	}

	public void setMoneyOrRabatt(float moneyOrRabatt) {
		this.moneyOrRabatt = moneyOrRabatt;
	}


	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getStopTime() {
		return this.stopTime;
	}

	public void setStopTime(Date stopTime) {
		this.stopTime = stopTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Boolean getIsUsed() {
		return isUsed;
	}

	public void setIsUsed(Boolean isUsed) {
		this.isUsed = isUsed;
	}

	public Date getUsedDate() {
		return usedDate;
	}

	public void setUsedDate(Date usedDate) {
		this.usedDate = usedDate;
	}

	public Integer getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public Integer getUsedPersonId() {
		return usedPersonId;
	}

	public void setUsedPersonId(Integer usedPersonId) {
		this.usedPersonId = usedPersonId;
	}

	public String getUsedPersonName() {
		return usedPersonName;
	}

	public void setUsedPersonName(String usedPersonName) {
		this.usedPersonName = usedPersonName;
	}
	public CouponMemberTemplate getCouponMemberTemplate() {
		return couponMemberTemplate;
	}
	public void setCouponMemberTemplate(CouponMemberTemplate couponMemberTemplate) {
		this.couponMemberTemplate = couponMemberTemplate;
	}
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}
	public boolean getShowHiden() {
		return showHiden;
	}
	public void setShowHiden(boolean showHiden) {
		this.showHiden = showHiden;
	}
	public Integer getEnterpriseId() {
		return enterpriseId;
	}
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}
	public Integer getBussiType() {
		return bussiType;
	}
	public void setBussiType(Integer bussiType) {
		this.bussiType = bussiType;
	}
	public Department getSendDep() {
		return sendDep;
	}
	public void setSendDep(Department sendDep) {
		this.sendDep = sendDep;
	}
	public String getSendDepName() {
		return sendDepName;
	}
	public void setSendDepName(String sendDepName) {
		this.sendDepName = sendDepName;
	}
	
}
