package com.ystech.mem.model;

// Generated 2014-3-18 20:55:47 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Emergencyhelp generated by hbm2java
 */
public class EmergencyHelp implements java.io.Serializable {

	private Integer dbid;
	private String coordinates;
	private Date createTime;
	private Date modifyTime;
	private String note;
	private Boolean status;
	private String operator;
	private String address;
	private String phone;
	private Member member;
	private String title;
	private Integer enterpriseId;
	public EmergencyHelp() {
	}

	public EmergencyHelp(String coordinates, Date createTime, Date modifyTime,
			String note, Boolean status, String operator) {
		this.coordinates = coordinates;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.note = note;
		this.status = status;
		this.operator = operator;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getCoordinates() {
		return this.coordinates;
	}

	public void setCoordinates(String coordinates) {
		this.coordinates = coordinates;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
}
