package com.ystech.mem.model;

import com.ystech.xwqr.model.sys.Area;


// Generated 2014-2-26 15:23:05 by Hibernate Tools 4.0.0

/**
 * Memberinfo generated by hbm2java
 */
public class MemberInfo implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private Area area;
	private String address;
	private Member member;

	public MemberInfo() {
	}

	public MemberInfo(String name, Integer areaId, String address,
			Integer memberId) {
		this.name = name;
		this.address = address;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}


}
