package com.ystech.mem.model;

// Generated 2014-2-26 10:47:34 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.weixin.model.WeixinGzuserinfo;
import com.ystech.xwqr.model.sys.User;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {
	//可用
	public static final Integer ENABLE=1;
	//不可用
	public static final Integer DISABLE=2;
	//线下会员
	public static final Integer OFFICEONLINE=1;
	//微信会员
	public static final Integer MICROMEMBER=2;
	//拥有奇瑞汽车
	public static final Integer HASQRCAR=1;
	//没有车
	public static final Integer HASNOCAR=2;
	//拥有其他品牌车
	public static final Integer HASCAR=3;
	
	public static final Integer AGENTAUTHCOMM=1;
	public static final Integer AGENTAUTHED=2;
	
	
	private Integer dbid;
	//会员编号
	private String no;
	//会员姓名
	private String name;
	//联系手机
	private String mobilePhone;
	//联系手机
	private String phone;
	//生日类型
	private Integer birthdayType;
	//生日
	private Date birthday;
	//性别
	private String sex;
	//会员级别
	private MemberShipLevel memberShipLevel;
	//车牌号
	private String carNo;
	//vinCode
	private String vinNo;
	//客户车型
	private String car;
	//备注
	private String note;
	private String nickName;
	
	//总积分
	private Integer totalPoint;
	//已消费积分
	private Integer consumpiontPoint;
	//剩余积分
	private Integer overagePiont;
	
	//储值余额
	private String balance;
	//总消费次数
	private Integer totalBuy;
	//销售总金额
	private Double totalMoney;
	//最后一次消费时间
	private Date lastBuyDate;
	
	
	//创建时间
	private Date createTime;
	//修改时间
	private Date modifyTime;
	
	//企业ID
	private Integer enterpriseId;
	//微信Id
	private String microId;
	//微信ID
	private WeixinGzuserinfo weixinGzuserinfo;
	//会员标签
	private String memTagIds;
	//会员标签
	private String memTagNames;
	
	
	//车主认证状态
	private Integer carMasterStatus;
	//认证时间
	private Date carMasterDate;
	
	
	
	
	//后期微信会员申请添加知道，1、我有奇瑞汽车；2、我没车；3、我有车
	private Integer hasCar;
	//在线预约次数
	private Integer onlineBookingNum;
	//最后一次联系时间
	private Date lastOnlineBookingDate;
	
	//最后一次联系时间
	private Date lastContactDate;
	
	//会员认证状态1、默认未认证，2、认证
	private Integer memAuthStatus;
	//会员认证时间
	private Date memAuthDate;
	private Date memLastAuthDate;
	
	//经纪人信息 /////////////////////////经纪人模块//////////////////////////////////////
	//是否开启推荐状态
	private Integer agentStatus;
	//权限开启日期
	private Date agentDate;
	//推荐人数
	private Integer agentNum;
	//推荐成功数
	private Integer agentSuccessNum;
	//银行
	private String payType;
	//账号
	private String accountNo;
	//返利总额
	private Float agentMoney;
	//积分
	private Integer agentPointNum;
	//身份证
	private String icard;
	//会员基础信息
	private MemberInfo memberInfo;
	
	//会员类型：0、为默认；1、员工；2、其他;3、微信外链接
	private Integer memType;
	//会员层级
	private Integer level;
	//发展经纪人人数
	private Integer totalNum;
	//认证数量
	private Integer carMasterNum;
	//上级
	private Member parent;
	//经纪人类型
	private Spread spread;
	//所属销售顾问
	private User user;
	
	private UseCarArea useCarArea;
	
	public Member() {
	}

	public Member(String no, String name, String mobilePhone, String phone,
			Integer memberShipLevleId, String carNo, String carGno,
			String engineNo, Integer brandId, Integer carSeriryId,
			Integer carModelId, String cusNote, String carNote, String sex,
			Integer totalPoint, Integer consumpiontPoint, Integer overagePiont,
			String creator, Date createTime, Date modifyTime, Integer status,
			String departmentName) {
		this.no = no;
		this.name = name;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.carNo = carNo;
		this.totalPoint = totalPoint;
		this.consumpiontPoint = consumpiontPoint;
		this.overagePiont = overagePiont;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public MemberShipLevel getMemberShipLevel() {
		return memberShipLevel;
	}

	public void setMemberShipLevel(MemberShipLevel memberShipLevel) {
		this.memberShipLevel = memberShipLevel;
	}
	
	public Integer getBirthdayType() {
		return birthdayType;
	}

	public void setBirthdayType(Integer birthdayType) {
		this.birthdayType = birthdayType;
	}

	public String getCarNo() {
		return this.carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}


	public String getVinNo() {
		return vinNo;
	}

	public void setVinNo(String vinNo) {
		this.vinNo = vinNo;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	public Integer getTotalPoint() {
		return this.totalPoint;
	}

	public void setTotalPoint(Integer totalPoint) {
		this.totalPoint = totalPoint;
	}

	public Integer getConsumpiontPoint() {
		return this.consumpiontPoint;
	}

	public void setConsumpiontPoint(Integer consumpiontPoint) {
		this.consumpiontPoint = consumpiontPoint;
	}

	public Integer getOveragePiont() {
		return this.overagePiont;
	}

	public void setOveragePiont(Integer overagePiont) {
		this.overagePiont = overagePiont;
	}


	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}


	public String getMicroId() {
		return microId;
	}

	public void setMicroId(String microId) {
		this.microId = microId;
	}


	public MemberInfo getMemberInfo() {
		return memberInfo;
	}

	public void setMemberInfo(MemberInfo memberInfo) {
		this.memberInfo = memberInfo;
	}


	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}


	public Integer getHasCar() {
		return hasCar;
	}

	public void setHasCar(Integer hasCar) {
		this.hasCar = hasCar;
	}

	public String getBalance() {
		return balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public Integer getOnlineBookingNum() {
		return onlineBookingNum;
	}

	public void setOnlineBookingNum(Integer onlineBookingNum) {
		this.onlineBookingNum = onlineBookingNum;
	}


	public String getMemTagIds() {
		return memTagIds;
	}

	public void setMemTagIds(String memTagIds) {
		this.memTagIds = memTagIds;
	}

	public String getMemTagNames() {
		return memTagNames;
	}

	public void setMemTagNames(String memTagNames) {
		this.memTagNames = memTagNames;
	}

	public WeixinGzuserinfo getWeixinGzuserinfo() {
		return weixinGzuserinfo;
	}

	public void setWeixinGzuserinfo(WeixinGzuserinfo weixinGzuserinfo) {
		this.weixinGzuserinfo = weixinGzuserinfo;
	}

	public Date getLastBuyDate() {
		return lastBuyDate;
	}

	public void setLastBuyDate(Date lastBuyDate) {
		this.lastBuyDate = lastBuyDate;
	}

	public Date getLastContactDate() {
		return lastContactDate;
	}

	public void setLastContactDate(Date lastContactDate) {
		this.lastContactDate = lastContactDate;
	}



	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Integer getTotalBuy() {
		return totalBuy;
	}

	public void setTotalBuy(Integer totalBuy) {
		this.totalBuy = totalBuy;
	}


	public Double getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getCar() {
		return car;
	}

	public void setCar(String car) {
		this.car = car;
	}

	public Integer getCarMasterStatus() {
		return carMasterStatus;
	}

	public void setCarMasterStatus(Integer carMasterStatus) {
		this.carMasterStatus = carMasterStatus;
	}

	public Date getCarMasterDate() {
		return carMasterDate;
	}

	public void setCarMasterDate(Date carMasterDate) {
		this.carMasterDate = carMasterDate;
	}

	public Date getLastOnlineBookingDate() {
		return lastOnlineBookingDate;
	}

	public void setLastOnlineBookingDate(Date lastOnlineBookingDate) {
		this.lastOnlineBookingDate = lastOnlineBookingDate;
	}

	public Integer getMemAuthStatus() {
		return memAuthStatus;
	}

	public void setMemAuthStatus(Integer memAuthStatus) {
		this.memAuthStatus = memAuthStatus;
	}

	public Date getMemAuthDate() {
		return memAuthDate;
	}

	public void setMemAuthDate(Date memAuthDate) {
		this.memAuthDate = memAuthDate;
	}

	public Integer getAgentStatus() {
		return agentStatus;
	}

	public void setAgentStatus(Integer agentStatus) {
		this.agentStatus = agentStatus;
	}

	public Date getAgentDate() {
		return agentDate;
	}

	public void setAgentDate(Date agentDate) {
		this.agentDate = agentDate;
	}

	public Integer getAgentNum() {
		return agentNum;
	}

	public void setAgentNum(Integer agentNum) {
		this.agentNum = agentNum;
	}

	public Integer getAgentSuccessNum() {
		return agentSuccessNum;
	}

	public void setAgentSuccessNum(Integer agentSuccessNum) {
		this.agentSuccessNum = agentSuccessNum;
	}

	public String getPayType() {
		return payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public Float getAgentMoney() {
		return agentMoney;
	}

	public void setAgentMoney(Float agentMoney) {
		this.agentMoney = agentMoney;
	}

	public Integer getAgentPointNum() {
		return agentPointNum;
	}

	public void setAgentPointNum(Integer agentPointNum) {
		this.agentPointNum = agentPointNum;
	}

	public Date getMemLastAuthDate() {
		return memLastAuthDate;
	}

	public void setMemLastAuthDate(Date memLastAuthDate) {
		this.memLastAuthDate = memLastAuthDate;
	}

	public String getIcard() {
		return icard;
	}

	public void setIcard(String icard) {
		this.icard = icard;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Integer getMemType() {
		return memType;
	}

	public void setMemType(Integer memType) {
		this.memType = memType;
	}

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}


	public Integer getTotalNum() {
		return totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	public Member getParent() {
		return parent;
	}

	public void setParent(Member parent) {
		this.parent = parent;
	}


	public Spread getSpread() {
		return spread;
	}

	public void setSpread(Spread spread) {
		this.spread = spread;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public UseCarArea getUseCarArea() {
		return useCarArea;
	}

	public void setUseCarArea(UseCarArea useCarArea) {
		this.useCarArea = useCarArea;
	}

	public Integer getCarMasterNum() {
		return carMasterNum;
	}

	public void setCarMasterNum(Integer carMasterNum) {
		this.carMasterNum = carMasterNum;
	}

	

}
