package com.ystech.mem.model;
// Generated 2016-8-7 10:09:40 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * MemMemtag generated by hbm2java
 */
public class MemTag implements java.io.Serializable {
	public static Integer COMM=1;
	public static Integer YEAS=2;
	private Integer dbid;
	private String name;
	private String note;
	private Date createDate;
	private Date modifyDate;
	private Integer num;
	//是否有用户在引用：1、正常；2、有引用
	private Integer status;
	//
	private Integer enterpriseId;

	public MemTag() {
	}

	public MemTag(String name, String note, Date createDate, Date modifyDate, Integer num) {
		this.name = name;
		this.note = note;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.num = num;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

}
