package com.ystech.mem.model;

// Generated 2014-2-25 14:48:58 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Onlinebooking generated by hbm2java
 */
public class OnlineBooking implements java.io.Serializable {
	//预约信息状态 为未查看状态
	public static final Integer NORMALL=1;
	//预约状态 已经查看
	public static final Integer CHECKED=2;
	//预约试乘试驾
	public static final String ONLINEBOOKIING="1";
	//预约保养维修
	public static final String ONLINEBOOKINGSAFETYMAINT="2";
	//预约续保年审
	public static final String ONLINEBOOKINGEXAMINED="3";
	//旧车置换
	public static final String ONLINEBOOKIINGOLDCARCHAGE="4";
	
	private Integer dbid;
	private String microId;
	private String name;
	private String mobilePhone;
	private Date bookingDate;
	private String phone;
	private String note;
	private String carModel;
	private String carSeriy;
	private String dealRecord;
	private String bookingType;
	private String area;
	private Integer status;
	private Date createTime;
	private Date modifyTime;
	private String operator;
	private Boolean isMember;
	private Boolean isCustomer;
	private Boolean isMessage;
	private String carPlate;
	private Integer enterpriseId;
	private Member member;
	
	//服务方式，1、自己来店；2、上面取车
	private Integer serviceType;
	//经纬度信息
	private String point;
	//地址标题
	private String addressTitle;
	//地址信息
	private String address;
	//预约取车时间：
	private String startTime;
	//预约结束时间
	private String endTime;

	public OnlineBooking() {
	}

	public OnlineBooking(String microId, String name, String mobilePhone,
			String phone, String note, String carModel, Integer status,
			Date createTime, Date modifyTime, String operator) {
		this.microId = microId;
		this.name = name;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.note = note;
		this.carModel = carModel;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.operator = operator;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getMicroId() {
		return this.microId;
	}

	public void setMicroId(String microId) {
		this.microId = microId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCarModel() {
		return this.carModel;
	}

	public Date getBookingDate() {
		return bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getCarSeriy() {
		return carSeriy;
	}

	public void setCarSeriy(String carSeriy) {
		this.carSeriy = carSeriy;
	}

	public String getDealRecord() {
		return dealRecord;
	}

	public void setDealRecord(String dealRecord) {
		this.dealRecord = dealRecord;
	}

	public String getBookingType() {
		return bookingType;
	}

	public void setBookingType(String bookingType) {
		this.bookingType = bookingType;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Boolean getIsMember() {
		return isMember;
	}

	public void setIsMember(Boolean isMember) {
		this.isMember = isMember;
	}

	public Boolean getIsCustomer() {
		return isCustomer;
	}

	public void setIsCustomer(Boolean isCustomer) {
		this.isCustomer = isCustomer;
	}

	public Boolean getIsMessage() {
		return isMessage;
	}

	public void setIsMessage(Boolean isMessage) {
		this.isMessage = isMessage;
	}

	public String getCarPlate() {
		return carPlate;
	}

	public void setCarPlate(String carPlate) {
		this.carPlate = carPlate;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Integer getServiceType() {
		return serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	public String getPoint() {
		return point;
	}

	public void setPoint(String point) {
		this.point = point;
	}

	public String getAddressTitle() {
		return addressTitle;
	}

	public void setAddressTitle(String addressTitle) {
		this.addressTitle = addressTitle;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

}
