package com.ystech.mem.model;

// Generated 2014-3-12 20:19:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Onlinebookingoldcarchanage generated by hbm2java
 */
public class OnlineBookingOldCarChanage extends OnlineBooking implements java.io.Serializable {

	private String unit;
	private Date carPlateDate;
	private String safetyContent;
	private Date safetyDueDate;
	private Boolean isExamed;
	private Boolean isMajorAccident;
	private String driveringNum;
	public OnlineBookingOldCarChanage() {
	}


	public OnlineBookingOldCarChanage(int dbid, String unit, Date carPlateDate,
			String safetyContent, Date safetyDueDate, Boolean isExamed,
			Boolean isMajorAccident) {
		this.unit = unit;
		this.carPlateDate = carPlateDate;
		this.safetyContent = safetyContent;
		this.safetyDueDate = safetyDueDate;
		this.isExamed = isExamed;
		this.isMajorAccident = isMajorAccident;
	}


	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getCarPlateDate() {
		return this.carPlateDate;
	}

	public void setCarPlateDate(Date carPlateDate) {
		this.carPlateDate = carPlateDate;
	}

	public String getSafetyContent() {
		return this.safetyContent;
	}

	public void setSafetyContent(String safetyContent) {
		this.safetyContent = safetyContent;
	}

	public Date getSafetyDueDate() {
		return this.safetyDueDate;
	}

	public void setSafetyDueDate(Date safetyDueDate) {
		this.safetyDueDate = safetyDueDate;
	}

	public Boolean getIsExamed() {
		return this.isExamed;
	}

	public void setIsExamed(Boolean isExamed) {
		this.isExamed = isExamed;
	}

	public Boolean getIsMajorAccident() {
		return this.isMajorAccident;
	}

	public void setIsMajorAccident(Boolean isMajorAccident) {
		this.isMajorAccident = isMajorAccident;
	}



	public String getDriveringNum() {
		return driveringNum;
	}


	public void setDriveringNum(String driveringNum) {
		this.driveringNum = driveringNum;
	}

}
