package com.ystech.mem.model;

// Generated 2014-3-12 20:19:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Onlinebookingsafety generated by hbm2java
 */
public class OnlineBookingExamined extends OnlineBooking implements java.io.Serializable {

	private Date plateDate;
	private String factoryModel;

	public OnlineBookingExamined() {
	}


	public OnlineBookingExamined(int dbid, String carPlate, Date plateDate,
			String factoryModel) {
		this.plateDate = plateDate;
		this.factoryModel = factoryModel;
	}




	public Date getPlateDate() {
		return this.plateDate;
	}

	public void setPlateDate(Date plateDate) {
		this.plateDate = plateDate;
	}

	public String getFactoryModel() {
		return this.factoryModel;
	}

	public void setFactoryModel(String factoryModel) {
		this.factoryModel = factoryModel;
	}

}
