package com.ystech.mem.model;

// Generated 2014-2-26 15:10:13 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Pointrecord generated by hbm2java
 */
public class PointRecord implements java.io.Serializable {
	public static Integer TYPEAGENT=1;
	public static Integer TYPECOMMON=1;
	private Integer dbid;
	private String pointFrom;
	private Integer num;
	private String note;
	private Date createTime;
	private Member member;
	private String creator;
	private Integer enterpriseId;
	//积分类型，1、为正常送积分；2、推荐客户向推荐人反积分
	private Integer type;
	private Integer recommendCustomerId;
	public PointRecord() {
	}

	public PointRecord(String pointFrom, Integer num, String note,
			Date createTime, Integer memberId, String creator) {
		this.pointFrom = pointFrom;
		this.num = num;
		this.note = note;
		this.createTime = createTime;
		this.creator = creator;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getPointFrom() {
		return this.pointFrom;
	}

	public void setPointFrom(String pointFrom) {
		this.pointFrom = pointFrom;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getRecommendCustomerId() {
		return recommendCustomerId;
	}

	public void setRecommendCustomerId(Integer recommendCustomerId) {
		this.recommendCustomerId = recommendCustomerId;
	}
	
}
