package com.ystech.mem.model;

// Generated 2016-4-12 9:35:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AgentFanli generated by hbm2java
 */
public class Reward implements java.io.Serializable {
	public static final int SUCCESS=1;
	public static final int REG=1;
	public static final int AGENT=1;
	private Integer dbid;
	//奖励来源
	private String rewardFrom;
	//奖励金额
	private Float rewardMoney;
	//备注
	private String note;
	//创建时间
	private Date createTime;
	//会员ID
	private Member member;
	//创建人
	private String creator;
	//推荐人ID
	private Integer recommendCustomerId;
	//奖励类型:1、客户成交奖励；2、注册经纪人奖励；3、推荐经纪人奖励
	private Integer rewardType;
	//企业ID
	private Integer enterpriseId;
	//红包发送状态
	private Integer turnBackStatus;
	
	private Date sendTime;

	public Reward() {
	}

	public Reward(String fanliFrom, Float fanliMoney, String note,
			Date createTime, Integer agentId, String creator,
			Integer recommendCustomerId) {
		this.note = note;
		this.createTime = createTime;
		this.creator = creator;
		this.recommendCustomerId = recommendCustomerId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}



	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Integer getRecommendCustomerId() {
		return this.recommendCustomerId;
	}

	public void setRecommendCustomerId(Integer recommendCustomerId) {
		this.recommendCustomerId = recommendCustomerId;
	}

	public String getRewardFrom() {
		return rewardFrom;
	}

	public void setRewardFrom(String rewardFrom) {
		this.rewardFrom = rewardFrom;
	}

	public Float getRewardMoney() {
		return rewardMoney;
	}

	public void setRewardMoney(Float rewardMoney) {
		this.rewardMoney = rewardMoney;
	}

	public Integer getRewardType() {
		return rewardType;
	}

	public void setRewardType(Integer rewardType) {
		this.rewardType = rewardType;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Integer getTurnBackStatus() {
		return turnBackStatus;
	}

	public void setTurnBackStatus(Integer turnBackStatus) {
		this.turnBackStatus = turnBackStatus;
	}

	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
	
}
