package com.ystech.mem.model;
// Generated 2015-12-20 12:48:42 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.ystech.weixin.model.WeixinKeyWord;

/**
 * PllmSSpread generated by hbm2java
 */
public class Spread implements java.io.Serializable {
	public final static String COMMJJR="老客户";
	private Integer dbid;
	private String name;
	private String note;
	private Integer spreadNum;
	private Integer scanCodeNum;
	private Date createDate;
	private Date modifyDate;
	private Integer weixinAccountId;
	private Integer countNum;
	private Integer enterpriseId;
	//1、系统默认；2、系统创建
	private Integer status;
	public Spread() {
	}

	public Spread(String name, String note, Integer spreadNum, Integer scanCodeNum, Date createDate,
			Date modifyDate) {
		this.name = name;
		this.note = note;
		this.spreadNum = spreadNum;
		this.scanCodeNum = scanCodeNum;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getSpreadNum() {
		return this.spreadNum;
	}

	public void setSpreadNum(Integer spreadNum) {
		this.spreadNum = spreadNum;
	}

	public Integer getScanCodeNum() {
		return this.scanCodeNum;
	}

	public void setScanCodeNum(Integer scanCodeNum) {
		this.scanCodeNum = scanCodeNum;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getWeixinAccountId() {
		return weixinAccountId;
	}

	public void setWeixinAccountId(Integer weixinAccountId) {
		this.weixinAccountId = weixinAccountId;
	}

	public Integer getCountNum() {
		return countNum;
	}

	public void setCountNum(Integer countNum) {
		this.countNum = countNum;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
