package com.ystech.mem.model;
// Generated 2015-12-20 12:48:42 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import com.ystech.weixin.model.WeixinGzuserinfo;
import com.ystech.weixin.model.WeixinKeyWordRole;

/**
 * PllmSSpreaddetail generated by hbm2java
 */
public class SpreadDetail implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String note;
	// 关注个数
	private Integer spreadNum;
	//扫描次数
	private Integer scanNum;
	//场景值场景值ID（字符串形式的ID）
	private String sceneStr;
	//获取的二维码ticket，
	private String ticket;
	//参数二维码
	private String qrcode;
	private Date createDate;
	private Date modifyDate;
	private Integer orderNum;
	//标签
	private String memTagIds;
	
	private String memTagNames;
	//会员等级
	private MemberShipLevel memberShipLevel;
	
	private WeixinKeyWordRole weixinKeyWordRole;
	
	private SpreadGroup spreadGroup;
	private Spread spread;
	
	//启用状态1、为启用；2、失效
	private Integer status;

	//经纪人生成推荐二维码
	private WeixinGzuserinfo weixinGzuserinfo;
	
	public SpreadDetail() {
	}

	public SpreadDetail(String name, String note, Integer spreadNum, Integer scanNum, String sceneId,
			String qrcode, Date createDate, Date modifyDate, Integer orderNum, Integer groupId, Integer spreadId) {
		this.name = name;
		this.note = note;
		this.spreadNum = spreadNum;
		this.scanNum = scanNum;
		this.qrcode = qrcode;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.orderNum = orderNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getSpreadNum() {
		return this.spreadNum;
	}

	public void setSpreadNum(Integer spreadNum) {
		this.spreadNum = spreadNum;
	}

	public Integer getScanNum() {
		return this.scanNum;
	}

	public void setScanNum(Integer scanNum) {
		this.scanNum = scanNum;
	}


	public String getSceneStr() {
		return sceneStr;
	}

	public void setSceneStr(String sceneStr) {
		this.sceneStr = sceneStr;
	}

	public String getTicket() {
		return ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public SpreadGroup getSpreadGroup() {
		return spreadGroup;
	}

	public void setSpreadGroup(SpreadGroup spreadGroup) {
		this.spreadGroup = spreadGroup;
	}

	public Spread getSpread() {
		return spread;
	}

	public void setSpread(Spread spread) {
		this.spread = spread;
	}


	public MemberShipLevel getMemberShipLevel() {
		return memberShipLevel;
	}

	public void setMemberShipLevel(MemberShipLevel memberShipLevel) {
		this.memberShipLevel = memberShipLevel;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public WeixinKeyWordRole getWeixinKeyWordRole() {
		return weixinKeyWordRole;
	}

	public void setWeixinKeyWordRole(WeixinKeyWordRole weixinKeyWordRole) {
		this.weixinKeyWordRole = weixinKeyWordRole;
	}

	public String getMemTagIds() {
		return memTagIds;
	}

	public void setMemTagIds(String memTagIds) {
		this.memTagIds = memTagIds;
	}

	public String getMemTagNames() {
		return memTagNames;
	}

	public void setMemTagNames(String memTagNames) {
		this.memTagNames = memTagNames;
	}

	public WeixinGzuserinfo getWeixinGzuserinfo() {
		return weixinGzuserinfo;
	}

	public void setWeixinGzuserinfo(WeixinGzuserinfo weixinGzuserinfo) {
		this.weixinGzuserinfo = weixinGzuserinfo;
	}
	

}
