package com.ystech.mem.model;

// Generated 2014-9-5 16:44:00 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.xwqr.model.sys.User;

/**
 * Storemoneyrecord generated by hbm2java
 */
public class StoreMoneyRecord implements java.io.Serializable {
	public static Integer SUCCESS=1;
	public static Integer VOID=2;
	private Integer dbid;
	private String actMoney;
	private String rechargeMoney;
	private Date rechargeTime;
	private Member member;
	private String rechargeExplain;
	private String note;
	private User user;
	private Date createTime;
	private Date modifyTime;
	private Integer payWay;
	private Integer status;

	public StoreMoneyRecord() {
	}

	public StoreMoneyRecord(String actMoney, String rechargeMoney,
			Date rechargeTime, Integer memberId, String rechargeExplain,
			String note, Integer creatorId, Date createTime, Date modifyTime,
			Integer payWay) {
		this.actMoney = actMoney;
		this.rechargeMoney = rechargeMoney;
		this.rechargeTime = rechargeTime;
		this.rechargeExplain = rechargeExplain;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.payWay = payWay;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getActMoney() {
		return this.actMoney;
	}

	public void setActMoney(String actMoney) {
		this.actMoney = actMoney;
	}

	public String getRechargeMoney() {
		return this.rechargeMoney;
	}

	public void setRechargeMoney(String rechargeMoney) {
		this.rechargeMoney = rechargeMoney;
	}

	public Date getRechargeTime() {
		return this.rechargeTime;
	}

	public void setRechargeTime(Date rechargeTime) {
		this.rechargeTime = rechargeTime;
	}


	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getRechargeExplain() {
		return this.rechargeExplain;
	}

	public void setRechargeExplain(String rechargeExplain) {
		this.rechargeExplain = rechargeExplain;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public User getUser() {
		return user;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getPayWay() {
		return this.payWay;
	}

	public void setPayWay(Integer payWay) {
		this.payWay = payWay;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
