package com.ystech.cust.model;

// Generated 2014-5-5 16:55:28 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Approvalrecord generated by hbm2java
 */
public class ApprovalRecord implements java.io.Serializable {

	private Integer dbid;
	private Integer approvalId;
	private String approvalName;
	private Date approvalTime;
	private Integer result;
	private String sugg;
	private OrderContract orderContract;

	public ApprovalRecord() {
	}

	public ApprovalRecord(Integer approvalId, String approvalName,
			Date approvalTime, Integer result, String sugg, Integer orderId) {
		this.approvalId = approvalId;
		this.approvalName = approvalName;
		this.approvalTime = approvalTime;
		this.result = result;
		this.sugg = sugg;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getApprovalId() {
		return this.approvalId;
	}

	public void setApprovalId(Integer approvalId) {
		this.approvalId = approvalId;
	}

	public String getApprovalName() {
		return this.approvalName;
	}

	public void setApprovalName(String approvalName) {
		this.approvalName = approvalName;
	}

	public Date getApprovalTime() {
		return this.approvalTime;
	}

	public void setApprovalTime(Date approvalTime) {
		this.approvalTime = approvalTime;
	}

	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}

	public String getSugg() {
		return this.sugg;
	}

	public void setSugg(String sugg) {
		this.sugg = sugg;
	}

	public OrderContract getOrderContract() {
		return orderContract;
	}

	public void setOrderContract(OrderContract orderContract) {
		this.orderContract = orderContract;
	}


}
