package com.ystech.cust.model;

// Generated 2014-7-2 0:03:26 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.xwqr.model.sys.Enterprise;

/**
 * Carvincode generated by hbm2java
 */
public class CarVinCode implements java.io.Serializable {

	private int dbid;
	private String vinCode;
	private String customerName;
	private String buffName;
	private Date createTime;
	private String car;
	private Enterprise enterprise;

	public CarVinCode() {
	}

	public CarVinCode(int dbid) {
		this.dbid = dbid;
	}

	public CarVinCode(int dbid, String vinCode, String customerName,
			String buffName, Date createTime, String car) {
		this.dbid = dbid;
		this.vinCode = vinCode;
		this.customerName = customerName;
		this.buffName = buffName;
		this.createTime = createTime;
		this.car = car;
	}

	public int getDbid() {
		return this.dbid;
	}

	public void setDbid(int dbid) {
		this.dbid = dbid;
	}

	public String getVinCode() {
		return this.vinCode;
	}

	public void setVinCode(String vinCode) {
		this.vinCode = vinCode;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getBuffName() {
		return this.buffName;
	}

	public void setBuffName(String buffName) {
		this.buffName = buffName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCar() {
		return this.car;
	}

	public void setCar(String car) {
		this.car = car;
	}

	public Enterprise getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

}
