package com.ystech.cust.model;

// Generated 2014-2-28 10:59:50 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.xwqr.set.model.Brand;
import com.ystech.xwqr.set.model.CarColor;
import com.ystech.xwqr.set.model.CarModel;
import com.ystech.xwqr.set.model.CarSeriy;

/**
 * Customerpidbookingrecord generated by hbm2java
 * 交车预约表
 */

public class CustomerPidBookingRecord implements java.io.Serializable {
	//打印合同状态 也是合同生成状态（交车）
	public static final Integer PRINT=1;
	//合同交易完成（归档）
	public static final Integer FINISHED=2;
	//等待审批,审批中
	public static final Integer STATUSWATING=3;
	//审批通过
	public static final Integer STATUSYEAS=4;
	//审批驳回
	public static final Integer STATUSNO=5;
	
	//交车预约未提交
	//物流部处理状态 0是待处理状态
	public static final Integer WLWATING=1;
	//物流部处理状态 1是处理状态
	public static final Integer WLDEALED=2;
	
	
	//1为有车
	public static final Integer HASCARORDERWIN=1;
	//2为在途
	public static final Integer HASCARORDERING=2;
	//3为无车
	public static final Integer HASCARORDERNO=3;
	
	//1出库核查默认状态
	public static final Integer OUTCHECKDEFAULT=1;
	//2为已经核查
	public static final Integer OUTCHECKED=2;
	
	//回访状态1、待回访，3、已经回访；2、需再次回访
	public static final Integer HFWATING=1;
	public static final Integer HFAGIN=2;
	public static final Integer HFED=3;
	
	//跨店销售邦车1、默认正常；2、跨店邦车申请中；3、审批同意；6、申请驳回(无审批驳回状态；审批驳回会重置交车预约）；4、已发车；5、已收车
	public static final Integer KDCOMM=1;
	public static final Integer KDAPPLAYING=2;
	public static final Integer KDYES=3;
	public static final Integer KDYSENDINGCAR=4;
	public static final Integer KDCARRECIVED=5;
	
	
	private Integer dbid;
	private Brand brand;
	private CarModel carModel;
	private CarSeriy carSeriy;
	private String carModelContent;
	private String spec;
	private CarColor carColor;
	private Date orderDate;
	private Boolean incompleteData;
	private Boolean approvaling;
	private Boolean approvalNotOther;
	private Boolean approvalNot;
	private Date bookingDate;
	private String webSite;
	private String vinCode;
	private String carSource;
	//1、新到车辆	2、预警一级	3、预警二级	4、自有一级	5、自有二级	6、自有三级	7、自有重点
	private Integer hasCarWl;
	private String note;
	private Customer customer;
	private Integer userId;
	private Date createTime;
	private Date modifyTime;
	//车源情况:1为有车，2为在途 3为无车 有车情况为true 为1，无车情况为false 0
	private Integer hasCarOrder;
	//该字段已经取消 无用
	private Boolean noCarOrder;
	//1、打印合合同；
	//（后续操作笑销售人员物流部填写交车信息；)
	//2、合同已经完成
	//3、取消合同（申请)
	//4、申请成功（申请成功）（）
	//5、申请失败()
	private Integer pidStatus;
	//物流备注
	private String wlNote;
	//物流部创建时间
	private Date wlCreateTime;
	//物流部创建人
	private String wlCreator;
	
	//物流部操作状态 0为交车预约未提交 1 为等待处理状态；2、为处理状态
	private Integer wlStatus;
	
	//销售顾问奖励金额
	private Integer rewardMoney;
	
	//出库权限核查1、为默认状态；2、为已核查
	public Integer outStockCheckStatus;
	
	//1、待回访，3、已经回访；2、需再次回访
	public Integer hfStatus;
	
	//跨店销售邦车1、默认正常；2、跨店邦车申请中；3、审批同意；4、申请驳回(无审批驳回状态；审批驳回会重置交车预约）
	public Integer kdStatus;
	
	
	//提报财务状态1、默认；2、提交
	private Integer cwStatus;
	//提报财务提交时间
	private Date cwDate;
	//审批状态：1、修改按揭默认，2、发起修改申请,3、修改审批驳回；4、修改申请同意
	private Integer cwAppStatus;
	//挂车物流处理状态：1 为等待处理状态；2、为处理状态
	private Integer cartrialerWlStatus;
	//挂车VIN码
	private String cartrialerVinCode;
	//车源情况:1为有车，2为在途 3为无车 有车情况为true 为1，无车情况为false 0
	private Integer cartrialerHasCarOrder;
	//物流备注
	private String cartrialerWlNote;
	//物流部创建时间
	private Date cartrialerWlCreateTime;
	public CustomerPidBookingRecord() {
	}

	public CustomerPidBookingRecord(Integer carModelid, String carModel,
			String spec, String color, Date orderDate, Boolean incompleteData,
			Boolean approvaling, Boolean approvalNotOther, Boolean approvalNot,
			Boolean hasCarOrder, Boolean noCarOrder, Date bookingDate,
			String webSite, String carSource, String hasCarWl, String note,
			Integer customerId) {
		this.spec = spec;
		this.orderDate = orderDate;
		this.incompleteData = incompleteData;
		this.approvaling = approvaling;
		this.approvalNotOther = approvalNotOther;
		this.approvalNot = approvalNot;
		this.noCarOrder = noCarOrder;
		this.bookingDate = bookingDate;
		this.webSite = webSite;
		this.carSource = carSource;
		this.note = note;
	}



	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public void setCarModel(CarModel carModel) {
		this.carModel = carModel;
	}

	public void setCarModelContent(String carModelContent) {
		this.carModelContent = carModelContent;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}


	public CarColor getCarColor() {
		return carColor;
	}

	public void setCarColor(CarColor carColor) {
		this.carColor = carColor;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Boolean getIncompleteData() {
		return this.incompleteData;
	}

	public void setIncompleteData(Boolean incompleteData) {
		this.incompleteData = incompleteData;
	}

	public Boolean getApprovaling() {
		return this.approvaling;
	}

	public void setApprovaling(Boolean approvaling) {
		this.approvaling = approvaling;
	}

	public Boolean getApprovalNotOther() {
		return this.approvalNotOther;
	}

	public void setApprovalNotOther(Boolean approvalNotOther) {
		this.approvalNotOther = approvalNotOther;
	}

	public Boolean getApprovalNot() {
		return this.approvalNot;
	}

	public void setApprovalNot(Boolean approvalNot) {
		this.approvalNot = approvalNot;
	}


	public Integer getHasCarOrder() {
		return hasCarOrder;
	}

	public void setHasCarOrder(Integer hasCarOrder) {
		this.hasCarOrder = hasCarOrder;
	}

	public Boolean getNoCarOrder() {
		return this.noCarOrder;
	}

	public void setNoCarOrder(Boolean noCarOrder) {
		this.noCarOrder = noCarOrder;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getCarSource() {
		return this.carSource;
	}

	public void setCarSource(String carSource) {
		this.carSource = carSource;
	}


	public Integer getHasCarWl() {
		return hasCarWl;
	}

	public void setHasCarWl(Integer hasCarWl) {
		this.hasCarWl = hasCarWl;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public CarModel getCarModel() {
		return carModel;
	}

	public String getCarModelContent() {
		return carModelContent;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getPidStatus() {
		return pidStatus;
	}

	public void setPidStatus(Integer pidStatus) {
		this.pidStatus = pidStatus;
	}

	public CarSeriy getCarSeriy() {
		return carSeriy;
	}

	public void setCarSeriy(CarSeriy carSeriy) {
		this.carSeriy = carSeriy;
	}

	public String getWlNote() {
		return wlNote;
	}

	public void setWlNote(String wlNote) {
		this.wlNote = wlNote;
	}

	public Date getWlCreateTime() {
		return wlCreateTime;
	}

	public void setWlCreateTime(Date wlCreateTime) {
		this.wlCreateTime = wlCreateTime;
	}

	public String getWlCreator() {
		return wlCreator;
	}

	public void setWlCreator(String wlCreator) {
		this.wlCreator = wlCreator;
	}


	public Integer getWlStatus() {
		return wlStatus;
	}

	public Integer getRewardMoney() {
		return rewardMoney;
	}

	public void setRewardMoney(Integer rewardMoney) {
		this.rewardMoney = rewardMoney;
	}

	public void setWlStatus(Integer wlStatus) {
		this.wlStatus = wlStatus;
	}

	public String getVinCode() {
		return vinCode;
	}

	public void setVinCode(String vinCode) {
		this.vinCode = vinCode;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public Integer getOutStockCheckStatus() {
		return outStockCheckStatus;
	}

	public void setOutStockCheckStatus(Integer outStockCheckStatus) {
		this.outStockCheckStatus = outStockCheckStatus;
	}

	public Integer getHfStatus() {
		return hfStatus;
	}

	public void setHfStatus(Integer hfStatus) {
		this.hfStatus = hfStatus;
	}

	public Integer getKdStatus() {
		return kdStatus;
	}

	public void setKdStatus(Integer kdStatus) {
		this.kdStatus = kdStatus;
	}

	public Integer getCwStatus() {
		return cwStatus;
	}

	public void setCwStatus(Integer cwStatus) {
		this.cwStatus = cwStatus;
	}

	public Date getCwDate() {
		return cwDate;
	}

	public void setCwDate(Date cwDate) {
		this.cwDate = cwDate;
	}

	public Integer getCwAppStatus() {
		return cwAppStatus;
	}

	public void setCwAppStatus(Integer cwAppStatus) {
		this.cwAppStatus = cwAppStatus;
	}

	public Integer getCartrialerWlStatus() {
		return cartrialerWlStatus;
	}

	public void setCartrialerWlStatus(Integer cartrialerWlStatus) {
		this.cartrialerWlStatus = cartrialerWlStatus;
	}

	public String getCartrialerVinCode() {
		return cartrialerVinCode;
	}

	public void setCartrialerVinCode(String cartrialerVinCode) {
		this.cartrialerVinCode = cartrialerVinCode;
	}

	public Integer getCartrialerHasCarOrder() {
		return cartrialerHasCarOrder;
	}

	public void setCartrialerHasCarOrder(Integer cartrialerHasCarOrder) {
		this.cartrialerHasCarOrder = cartrialerHasCarOrder;
	}

	public String getCartrialerWlNote() {
		return cartrialerWlNote;
	}

	public void setCartrialerWlNote(String cartrialerWlNote) {
		this.cartrialerWlNote = cartrialerWlNote;
	}

	public Date getCartrialerWlCreateTime() {
		return cartrialerWlCreateTime;
	}

	public void setCartrialerWlCreateTime(Date cartrialerWlCreateTime) {
		this.cartrialerWlCreateTime = cartrialerWlCreateTime;
	}
	
}
