package com.ystech.cust.model;

// Generated 2014-2-27 13:48:51 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * 来电登记记录信息表
 * Customershoppingrecord generated by hbm2java
 */
public class CustomerShoppingRecord implements java.io.Serializable {
	public static Integer COMETYPESHOPING=1;
	public static Integer COMETYPEPHONE=2;
	public static Integer COMETYPESACT=3;
	public static Integer COMETYPEOTHER=4;
	private Integer dbid;
	private Date comeInDate;
	private String comeInTime;
	private String farwayTime;
	private Integer waitingTime;
	private String receptionExperience;
	private Integer isTryDriver;
	private String tryDriver;
	private Boolean isFirst;
	private Boolean isGetCar;
	private String carModel;
	private Integer customerNum;
	private Customer customer;
	//来店类型
	private Integer comeType;

	public CustomerShoppingRecord() {
	}

	public CustomerShoppingRecord(Integer departmentId, Date comeInDate,
			Integer comeInTime, Integer farwayTime, Integer waitingTime,
			String receptionExperience, Boolean isTryDriver, String tryDriver,
			Boolean isFirst, Boolean isGetCar, String carModel,
			Integer customerNum, Integer customerId, Integer comeType) {
		this.comeInDate = comeInDate;
		this.waitingTime = waitingTime;
		this.receptionExperience = receptionExperience;
		this.tryDriver = tryDriver;
		this.isFirst = isFirst;
		this.isGetCar = isGetCar;
		this.carModel = carModel;
		this.customerNum = customerNum;
		this.comeType = comeType;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}



	public Date getComeInDate() {
		return this.comeInDate;
	}

	public void setComeInDate(Date comeInDate) {
		this.comeInDate = comeInDate;
	}

	public String getComeInTime() {
		return this.comeInTime;
	}

	public void setComeInTime(String comeInTime) {
		this.comeInTime = comeInTime;
	}

	public String getFarwayTime() {
		return this.farwayTime;
	}

	public void setFarwayTime(String farwayTime) {
		this.farwayTime = farwayTime;
	}

	public Integer getWaitingTime() {
		return this.waitingTime;
	}

	public void setWaitingTime(Integer waitingTime) {
		this.waitingTime = waitingTime;
	}

	public String getReceptionExperience() {
		return this.receptionExperience;
	}

	public void setReceptionExperience(String receptionExperience) {
		this.receptionExperience = receptionExperience;
	}

	public Integer getIsTryDriver() {
		return this.isTryDriver;
	}

	public void setIsTryDriver(Integer isTryDriver) {
		this.isTryDriver = isTryDriver;
	}

	public String getTryDriver() {
		return this.tryDriver;
	}

	public void setTryDriver(String tryDriver) {
		this.tryDriver = tryDriver;
	}

	public Boolean getIsFirst() {
		return this.isFirst;
	}

	public void setIsFirst(Boolean isFirst) {
		this.isFirst = isFirst;
	}

	public Boolean getIsGetCar() {
		return this.isGetCar;
	}

	public void setIsGetCar(Boolean isGetCar) {
		this.isGetCar = isGetCar;
	}

	public String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	public Integer getCustomerNum() {
		return this.customerNum;
	}

	public void setCustomerNum(Integer customerNum) {
		this.customerNum = customerNum;
	}


	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getComeType() {
		return this.comeType;
	}

	public void setComeType(Integer comeType) {
		this.comeType = comeType;
	}

}
