package com.ystech.cust.model;

// Generated 2018-5-24 17:24:07 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CustCustomertrackstatic generated by hbm2java
 */
public class CustomerTrackStatic implements java.io.Serializable {

	private Integer dbid;
	private Integer entId;
	private String entName;
	private Integer depId;
	private String depName;
	private Integer salerId;
	private String salerName;
	private Date dayDate;
	private Integer trackTotalNum;
	private Integer trackedTotalNum;
	private Integer trackNotNum;

	public CustomerTrackStatic() {
	}

	public CustomerTrackStatic(Integer entId, String entName,
			Integer depId, String depName, Integer salerId, String salerName,
			Date dayDate, Integer trackTotalNum, Integer trackedTotalNum,
			Integer trackNotNum) {
		this.entId = entId;
		this.entName = entName;
		this.depId = depId;
		this.depName = depName;
		this.salerId = salerId;
		this.salerName = salerName;
		this.dayDate = dayDate;
		this.trackTotalNum = trackTotalNum;
		this.trackedTotalNum = trackedTotalNum;
		this.trackNotNum = trackNotNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getEntId() {
		return this.entId;
	}

	public void setEntId(Integer entId) {
		this.entId = entId;
	}

	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public Integer getDepId() {
		return this.depId;
	}

	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public Integer getSalerId() {
		return this.salerId;
	}

	public void setSalerId(Integer salerId) {
		this.salerId = salerId;
	}

	public String getSalerName() {
		return this.salerName;
	}

	public void setSalerName(String salerName) {
		this.salerName = salerName;
	}

	public Date getDayDate() {
		return this.dayDate;
	}

	public void setDayDate(Date dayDate) {
		this.dayDate = dayDate;
	}

	public Integer getTrackTotalNum() {
		return this.trackTotalNum;
	}

	public void setTrackTotalNum(Integer trackTotalNum) {
		this.trackTotalNum = trackTotalNum;
	}

	public Integer getTrackedTotalNum() {
		return this.trackedTotalNum;
	}

	public void setTrackedTotalNum(Integer trackedTotalNum) {
		this.trackedTotalNum = trackedTotalNum;
	}

	public Integer getTrackNotNum() {
		return this.trackNotNum;
	}

	public void setTrackNotNum(Integer trackNotNum) {
		this.trackNotNum = trackNotNum;
	}

}
