package com.ystech.cust.model;

// Generated 2014-2-23 13:31:11 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.ystech.agent.model.RecommendCustomer;
import com.ystech.xwqr.model.sys.Area;
import com.ystech.xwqr.model.sys.Department;
import com.ystech.xwqr.model.sys.Enterprise;
import com.ystech.xwqr.model.sys.User;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {
	//成交状态0.默认状态；1、表示购车成功；2、表示购买其他车；3、表示取消买车;
	public static final Integer NORMAL=0;
	public static final Integer SUCCESS=1;
	public static final Integer BUYOTHER=2;
	public static final Integer CANCCEL=3;
	
	//是否生成订单
	public static final Integer ORDERNOT=0;
	public static final Integer ORDERYEAS=1;

	//客户类型
	public static final Integer CUSTOMERTYPECOMM=1;
	public static final Integer CUSTOMERTYPENETTOW=2;
	//DMS状态 0、为正常状态；1、为dms系统以及买卖（卖车方承担回访义务）；2、位dms系统未买卖（进货承担回访义务）
	public static final Integer DMSCOMM=0;
	public static final Integer DMSSALER=1;
	public static final Integer DMSSURCE=2;
	
	//跨店销售 1、正常；2、是跨店
	public static final Integer KDCOMM=1;
	public static final Integer KDYEAS=2;
	
	
	private Integer dbid;
	private String sn;
	private CustomerPhase customerPhase;
	private CustomerPhase firstCustomerPhase;
	private String name;
	private String sex;
	private String mobilePhone;
	private String phone;
	private String email;
	private String qq;
	private String family;
	private String companyName1;
	private String hobby;
	private Paperwork paperwork;
	private String icard;
	private Area area;
	private String address;
	private String zipCode;
	private Date gbirthday;
	private Date nbirthday;
	private String carModelStr;
	private Profession profession;
	private Industry industry;
	private Educational educational;
	private String note;
	private String navPrice;
	private String carColorStr;
	private String bussiStaff;
	private User user;
	private Date createFolderTime;
	private String salesConsultant;
	private String showRoomManager;
	private String interests;
	//1、前台接待 进店；2、前台接待 来电；3、网销导入；4、活动；5、其他
	private CustomerType customerType;
	private Integer age;
	//客户跟踪信息(此类应该不会包含重复数据)
	private CustomerBussi customerBussi;
	//同城交叉客户
	private CustomerLastBussi customerLastBussi;
	//客户来电登记信息
	private CustomerShoppingRecord customerShoppingRecord;
	
	private CustomerPidBookingRecord customerPidBookingRecord;
	//图片上传
	private CustomerImageApproval customerImageApproval;
	//追踪记录超时信息表类
	private TimeoutsTrackRecord timeoutsTrackRecord;
	
	private OrderContract orderContract;
	//登记客户部门
	private Department department;
	
	//成交时间客户所在部门
	private Department successDepartment;
	
	//客户状态；0为默认创建状态、1、客户成交、2、客户流失购买其他车、3、客户流失构成计划取消；
	private Integer lastResult;
	
	//是否创建了订单，未创建0，已经创建1
	private Integer orderContractStatus;
	
	//客户类型，自有店客户1（系统默认），二网客户2
	private Integer recordType;
	
	private Enterprise enterprise;
	//二网客户 经销商信息
	private Distributor distributor;
	
	//0、为正常状态；1、为dms系统以及买卖（卖车方承担回访义务）；2、位dms系统未买卖（进货承担回访义务）
	private Integer dmsStatus;
	//跨店销售状态：1、为正常；2、为跨店销售
	private Integer kdStatus;
	//车辆原始进货商
	private Enterprise sourceEnterprise;
	
	//到店次数 默认为1；到店一次加一次
	public Integer comeShopNum;
	//互动次数，回访客户次数 默认为0
	public Integer trackNum;
	//客户来源
	public CustomerInfrom customerInfrom;
	private RecommendCustomer recommendCustomer;
	//客户业务类型：1、小车客户；2、卡车客户
	private Integer bussiType;
	//加挂客户状：1、正常；2:加挂(订单加挂车时添加）
	private Integer custCartrialerStatus;
	//客户贷款状态 1、正常；2、贷款；3、不加挂贷款
	private Integer loanType;
	//贷款客户金融部是否转登记：1、正常；2、已转登记
	private Integer loanFinStatus;
	//客户到店状态：1、未到店；2、已到店；3、二次到店
	public Integer comeShopStatus;
	//接待谈判人员
	public String receptierSalerName;
	//接待谈判人员
	public User receptierSaler;
	//邀约人员
	public String invitationSalerName;
	//邀约人员
	public User invitationSaler;
	//到店时间
	public Date comeShopDate;
	//二次到店时间
	public Date twoComeShopDate;
	//试驾时间
	public Date tryCarDate;
	//试驾状态 1、未试驾；2、已经试驾
	public Integer tryCarStatus;
	private Set customertracks = new HashSet(0);
	private Set customerbussis = new HashSet(0);

	public Customer() {
	}

	public Customer(String sn, Integer level, String name, String sex,
			String mobilePhone, String phone, String email, String qq,
			String family, String companyName1, String hobby, Integer zjlxType,
			String icard, Integer areaId, String address, String zipCode,
			Date gbirthday, Date nbirthday, Integer professionId,
			Integer industryId, String note, String ywy, Date createFolderTime,
			String zlfs, String ztjl, Set customertracks,
			Set customerbussis) {
		this.sn = sn;
		this.name = name;
		this.sex = sex;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.email = email;
		this.qq = qq;
		this.family = family;
		this.companyName1 = companyName1;
		this.hobby = hobby;
		this.icard = icard;
		this.address = address;
		this.zipCode = zipCode;
		this.gbirthday = gbirthday;
		this.nbirthday = nbirthday;
		this.note = note;
		this.createFolderTime = createFolderTime;
		this.customertracks = customertracks;
		this.customerbussis = customerbussis;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getFamily() {
		return this.family;
	}

	public void setFamily(String family) {
		this.family = family;
	}

	public String getCompanyName1() {
		return this.companyName1;
	}

	public void setCompanyName1(String companyName1) {
		this.companyName1 = companyName1;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}


	public String getIcard() {
		return this.icard;
	}

	public void setIcard(String icard) {
		this.icard = icard;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public Date getGbirthday() {
		return this.gbirthday;
	}

	public void setGbirthday(Date gbirthday) {
		this.gbirthday = gbirthday;
	}

	public Date getNbirthday() {
		return this.nbirthday;
	}

	public void setNbirthday(Date nbirthday) {
		this.nbirthday = nbirthday;
	}

	public Profession getProfession() {
		return profession;
	}

	public void setProfession(Profession profession) {
		this.profession = profession;
	}


	public Industry getIndustry() {
		return industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public Educational getEducational() {
		return educational;
	}

	public void setEducational(Educational educational) {
		this.educational = educational;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	public String getBussiStaff() {
		return bussiStaff;
	}

	public void setBussiStaff(String bussiStaff) {
		this.bussiStaff = bussiStaff;
	}

	public Date getCreateFolderTime() {
		return this.createFolderTime;
	}

	public void setCreateFolderTime(Date createFolderTime) {
		this.createFolderTime = createFolderTime;
	}

	public String getSalesConsultant() {
		return salesConsultant;
	}

	public void setSalesConsultant(String salesConsultant) {
		this.salesConsultant = salesConsultant;
	}


	public String getShowRoomManager() {
		return showRoomManager;
	}

	public void setShowRoomManager(String showRoomManager) {
		this.showRoomManager = showRoomManager;
	}


	public Set getCustomertracks() {
		return this.customertracks;
	}

	public void setCustomertracks(Set customertracks) {
		this.customertracks = customertracks;
	}

	public Set getCustomerbussis() {
		return this.customerbussis;
	}

	public void setCustomerbussis(Set customerbussis) {
		this.customerbussis = customerbussis;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Paperwork getPaperwork() {
		return paperwork;
	}

	public void setPaperwork(Paperwork paperwork) {
		this.paperwork = paperwork;
	}

	public CustomerPhase getCustomerPhase() {
		return customerPhase;
	}

	public void setCustomerPhase(CustomerPhase customerPhase) {
		this.customerPhase = customerPhase;
	}

	public CustomerBussi getCustomerBussi() {
		return customerBussi;
	}

	public void setCustomerBussi(CustomerBussi customerBussi) {
		this.customerBussi = customerBussi;
	}

	public CustomerLastBussi getCustomerLastBussi() {
		return customerLastBussi;
	}

	public void setCustomerLastBussi(CustomerLastBussi customerLastBussi) {
		this.customerLastBussi = customerLastBussi;
	}

	public Integer getLastResult() {
		return lastResult;
	}

	public void setLastResult(Integer lastResult) {
		this.lastResult = lastResult;
	}

	public CustomerShoppingRecord getCustomerShoppingRecord() {
		return customerShoppingRecord;
	}

	public void setCustomerShoppingRecord(
			CustomerShoppingRecord customerShoppingRecord) {
		this.customerShoppingRecord = customerShoppingRecord;
	}

	public String getInterests() {
		return interests;
	}

	public void setInterests(String interests) {
		this.interests = interests;
	}

	public Integer getOrderContractStatus() {
		return orderContractStatus;
	}

	public void setOrderContractStatus(Integer orderContractStatus) {
		this.orderContractStatus = orderContractStatus;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public CustomerPidBookingRecord getCustomerPidBookingRecord() {
		return customerPidBookingRecord;
	}

	public void setCustomerPidBookingRecord(
			CustomerPidBookingRecord customerPidBookingRecord) {
		this.customerPidBookingRecord = customerPidBookingRecord;
	}

	public OrderContract getOrderContract() {
		return orderContract;
	}

	public void setOrderContract(OrderContract orderContract) {
		this.orderContract = orderContract;
	}


	public CustomerPhase getFirstCustomerPhase() {
		return firstCustomerPhase;
	}

	public void setFirstCustomerPhase(CustomerPhase firstCustomerPhase) {
		this.firstCustomerPhase = firstCustomerPhase;
	}

	public TimeoutsTrackRecord getTimeoutsTrackRecord() {
		return timeoutsTrackRecord;
	}

	public void setTimeoutsTrackRecord(TimeoutsTrackRecord timeoutsTrackRecord) {
		this.timeoutsTrackRecord = timeoutsTrackRecord;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}


	public Integer getRecordType() {
		return recordType;
	}

	public void setRecordType(Integer recordType) {
		this.recordType = recordType;
	}


	public Department getSuccessDepartment() {
		return successDepartment;
	}

	public void setSuccessDepartment(Department successDepartment) {
		this.successDepartment = successDepartment;
	}

	public CustomerImageApproval getCustomerImageApproval() {
		return customerImageApproval;
	}

	public void setCustomerImageApproval(CustomerImageApproval customerImageApproval) {
		this.customerImageApproval = customerImageApproval;
	}

	public Enterprise getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

	public Distributor getDistributor() {
		return distributor;
	}

	public void setDistributor(Distributor distributor) {
		this.distributor = distributor;
	}

	public Integer getDmsStatus() {
		return dmsStatus;
	}

	public void setDmsStatus(Integer dmsStatus) {
		this.dmsStatus = dmsStatus;
	}

	public Integer getKdStatus() {
		return kdStatus;
	}

	public void setKdStatus(Integer kdStatus) {
		this.kdStatus = kdStatus;
	}

	public Enterprise getSourceEnterprise() {
		return sourceEnterprise;
	}

	public void setSourceEnterprise(Enterprise sourceEnterprise) {
		this.sourceEnterprise = sourceEnterprise;
	}

	public Integer getComeShopNum() {
		return comeShopNum;
	}

	public void setComeShopNum(Integer comeShopNum) {
		this.comeShopNum = comeShopNum;
	}

	public Integer getTrackNum() {
		return trackNum;
	}

	public void setTrackNum(Integer trackNum) {
		this.trackNum = trackNum;
	}

	public CustomerInfrom getCustomerInfrom() {
		return customerInfrom;
	}

	public void setCustomerInfrom(CustomerInfrom customerInfrom) {
		this.customerInfrom = customerInfrom;
	}

	public RecommendCustomer getRecommendCustomer() {
		return recommendCustomer;
	}

	public void setRecommendCustomer(RecommendCustomer recommendCustomer) {
		this.recommendCustomer = recommendCustomer;
	}

	public Integer getBussiType() {
		return bussiType;
	}

	public void setBussiType(Integer bussiType) {
		this.bussiType = bussiType;
	}

	public Integer getCustCartrialerStatus() {
		return custCartrialerStatus;
	}

	public void setCustCartrialerStatus(Integer custCartrialerStatus) {
		this.custCartrialerStatus = custCartrialerStatus;
	}

	public Integer getLoanType() {
		return loanType;
	}

	public void setLoanType(Integer loanType) {
		this.loanType = loanType;
	}

	public Integer getLoanFinStatus() {
		return loanFinStatus;
	}

	public void setLoanFinStatus(Integer loanFinStatus) {
		this.loanFinStatus = loanFinStatus;
	}

	public String getCarModelStr() {
		return carModelStr;
	}

	public void setCarModelStr(String carModelStr) {
		this.carModelStr = carModelStr;
	}

	public String getNavPrice() {
		return navPrice;
	}

	public void setNavPrice(String navPrice) {
		this.navPrice = navPrice;
	}

	public String getCarColorStr() {
		return carColorStr;
	}

	public void setCarColorStr(String carColorStr) {
		this.carColorStr = carColorStr;
	}

	public Integer getComeShopStatus() {
		return comeShopStatus;
	}

	public void setComeShopStatus(Integer comeShopStatus) {
		this.comeShopStatus = comeShopStatus;
	}

	public String getReceptierSalerName() {
		return receptierSalerName;
	}

	public void setReceptierSalerName(String receptierSalerName) {
		this.receptierSalerName = receptierSalerName;
	}

	public User getReceptierSaler() {
		return receptierSaler;
	}

	public void setReceptierSaler(User receptierSaler) {
		this.receptierSaler = receptierSaler;
	}

	public String getInvitationSalerName() {
		return invitationSalerName;
	}

	public void setInvitationSalerName(String invitationSalerName) {
		this.invitationSalerName = invitationSalerName;
	}

	public User getInvitationSaler() {
		return invitationSaler;
	}

	public void setInvitationSaler(User invitationSaler) {
		this.invitationSaler = invitationSaler;
	}

	public Date getComeShopDate() {
		return comeShopDate;
	}

	public void setComeShopDate(Date comeShopDate) {
		this.comeShopDate = comeShopDate;
	}

	public Date getTwoComeShopDate() {
		return twoComeShopDate;
	}

	public void setTwoComeShopDate(Date twoComeShopDate) {
		this.twoComeShopDate = twoComeShopDate;
	}

	public Date getTryCarDate() {
		return tryCarDate;
	}

	public void setTryCarDate(Date tryCarDate) {
		this.tryCarDate = tryCarDate;
	}

	public Integer getTryCarStatus() {
		return tryCarStatus;
	}

	public void setTryCarStatus(Integer tryCarStatus) {
		this.tryCarStatus = tryCarStatus;
	}

	public CustomerType getCustomerType() {
		return customerType;
	}

	public void setCustomerType(CustomerType customerType) {
		this.customerType = customerType;
	}
	
}
