package com.ystech.cust.model;

import java.util.Date;

// Generated 2015-10-10 17:56:18 by Hibernate Tools 4.0.0

/**
 * Customerimageapproval generated by hbm2java
 */
public class CustomerImageApproval implements java.io.Serializable {
	//图片上传状态 1、未上传
	public static final Integer UPLOADSTATSCOMM=1;
	//图片上传状态 2、上传完成（待审批）
	public static final Integer UPLOADSTATSUPLOADED=2;
	//图片上传 3、审批驳回
	public static final Integer UPLOADDIS=3;
	//图片上传4、审批通过
	public static final Integer UPLOADYEAS=4;

	//status 1为默认
	public static final Integer STATUSCOMM=1;
	//status 2上传中
	public static final Integer STATUSUPLOADING=2;
	//status 3上传完成
	public static final Integer STATUSUPLOADED=3;
	private Integer dbid;
	private Customer customer;
	private Integer handCarStatus;
	private String handCarApproval;
	//1、未上传；2、上传完成（待审批）；3、审批驳回；4、审批通过
	private Integer drivingStatus;
	private String drivingApproval;
	//图片任务上传状态：1为默认；2、上传中；3、上传完成
	private Integer status;
	private Date successApplayDate;

	public CustomerImageApproval() {
	}

	public CustomerImageApproval(Integer customerId, Integer handCarStatus,
			String handCarApproval, Integer drivingStatus,
			String drivingApproval, Integer status) {
		this.handCarStatus = handCarStatus;
		this.handCarApproval = handCarApproval;
		this.drivingStatus = drivingStatus;
		this.drivingApproval = drivingApproval;
		this.status = status;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getHandCarStatus() {
		return this.handCarStatus;
	}

	public void setHandCarStatus(Integer handCarStatus) {
		this.handCarStatus = handCarStatus;
	}

	public String getHandCarApproval() {
		return this.handCarApproval;
	}

	public void setHandCarApproval(String handCarApproval) {
		this.handCarApproval = handCarApproval;
	}

	public Integer getDrivingStatus() {
		return this.drivingStatus;
	}

	public void setDrivingStatus(Integer drivingStatus) {
		this.drivingStatus = drivingStatus;
	}

	public String getDrivingApproval() {
		return this.drivingApproval;
	}

	public void setDrivingApproval(String drivingApproval) {
		this.drivingApproval = drivingApproval;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getSuccessApplayDate() {
		return successApplayDate;
	}

	public void setSuccessApplayDate(Date successApplayDate) {
		this.successApplayDate = successApplayDate;
	}


}
