package com.ystech.cust.model;

// Generated 2015-6-2 15:42:34 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Customerpidbookingcancelrecord generated by hbm2java
 */
public class CustomerPidBookingCancelRecord implements java.io.Serializable {

	private Integer dbid;
	private Integer customerId;
	private Date bookingDate;

	public CustomerPidBookingCancelRecord() {
	}

	public CustomerPidBookingCancelRecord(Integer customerId, Date bookingDate) {
		this.customerId = customerId;
		this.bookingDate = bookingDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

}
