package com.ystech.cust.model;

// Generated 2014-2-23 13:31:11 by Hibernate Tools 4.0.0


/**
 * des：市场邀约活动回访客户销售顾问统计记录bean
 * Customertrack generated by hbm2java
 */
public class CustomerTrackMarketingCount implements java.io.Serializable {
	private String depName;
	private String userName;
	private Integer total;
	private Integer accTotal;
	private Integer waitingTotal;
	private Integer disTotal;
	public String getDepName() {
		return depName;
	}
	public void setDepName(String depName) {
		this.depName = depName;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public Integer getTotal() {
		return total;
	}
	public void setTotal(Integer total) {
		this.total = total;
	}
	public Integer getAccTotal() {
		return accTotal;
	}
	public void setAccTotal(Integer accTotal) {
		this.accTotal = accTotal;
	}
	public Integer getWaitingTotal() {
		return waitingTotal;
	}
	public void setWaitingTotal(Integer waitingTotal) {
		this.waitingTotal = waitingTotal;
	}
	public Integer getDisTotal() {
		return disTotal;
	}
	public void setDisTotal(Integer disTotal) {
		this.disTotal = disTotal;
	}
	
}
	
