package com.ystech.cust.model;

// Generated 2014-2-23 13:31:11 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Customertrack generated by hbm2java
 */
public class CustomerTrack implements java.io.Serializable {
	//阅读状态 1、为默认；2、已读
	public static Integer COMMON=1;
	public static Integer COMMONREADED=2;
	//回访类型：1、日常关系维护；2、普通邀约到店（邀约客户到店看车）；3、活动邀约到店
	public static Integer TYPECOMM=1;
	public static Integer TYPENORMAL=2;
	public static Integer TYPEACT=3;
	//阅读状态 1、为默认；2、是第一添加
	public static Integer FIRSTSTATUSCOMM=1;
	public static Integer FIRSTSTATUSADD=2;
	
	//任务创建来源分类 1、创建客户创建任务
	public static Integer TASkCREATETYPECREATECUSTOMER=1;
	//任务创建来源分类 2、客户回访创建任务
	public static Integer TASKCREATETYPETRACK=2;
	//任务创建来源分类 3、流失客户转登记客户创建任务
	public static Integer TASKCREATEFLOWTURNCUSTOMER=3;
	//任务创建来源分类 4、订单客户流失创建任务
	public static Integer TASKCREATEORDERFLOWCUSTOMER=4;
	//任务创建来源分类 5、其他情况创建
	public static Integer TASKCREATEOROTHER=5;
	
	//客户超时统计类型 I类H、A、B、C 超时统计
	public static Integer CUSTOMERPAHSEONE=1;
	//客户超时统计类型 II类 O、L、F 无需超时统计
	public static Integer CUSTOMERPAHSETWO=2;
	
	//创建任务类型 1、默认状态
	public static Integer TASKFINISHTYPECOMM=1;
	//创建任务类型 2、正常回访关闭
	public static Integer TASKFINISHTYPETRACKED=2;
	//创建任务类型 3、提报订单关闭
	public static Integer TASKFINISHTYPEORDER=3;
	//创建任务类型 4、提报订单关闭
	public static Integer TASKFINISHTYPECUSTOMERFLOW=4;

	//任务处理状态  1、任务创建
	public static Integer TASKDEALSTATUSCREATE=1;
	//任务处理状态  2、任务已经处理
	public static Integer TASKDEALSTATUSDEALED=2;
	//任务处理状态  2、任务关闭（流失、提报订单）
	public static Integer TASKDEALSTATUSCLOSED=3;
	
	//任务超时状态  1、任务创建默认正常
	public static Integer TASKOVERTIMESTATUSCOMM=1;
	//任务超时状态  2、任务创建已经超时
	public static Integer TASKOVERTIMESTATUSED=2;
	
	//任务类型 1、次日回访
	public static Integer TASKTYPENEXTDAYTRACK=1;
	//任务类型 2、跟踪回访
	public static Integer TASKTYPETRACK=2;
	
	//任务超时考核状态 1、正常
	public static Integer TASKOVERTIMEASSEMENTSTATECOMM=1;
	//任务超时考核状态、2、异常（H->O,C->L)已经超时，数据处理
	public static Integer TASKOVERTIMEASSEMENTSTATEABNORMAL=2;
	
	private Integer dbid;
	//客户信息
	private Customer customer;
	//跟踪日期（处理 回访日期）
	private Date trackDate;
	//跟踪方法
	private Integer trackMethod;
	//跟踪内容
	private String trackContent;
	//反馈结果
	private String result;
	//应对措施
	private String feedBackResult;
	//处理方法
	private String dealMethod;
	//跟踪钱级别
	private CustomerPhase beforeCustomerPhase;
	//跟踪后级别
	private CustomerPhase afterCustomerPhase;
	//下次跟踪时间
	private Date nextReservationTime;
	//展厅经理意见
	private String showroomManagerSuggested;
	//用户Id
	private Integer userId;
	//创建时间
	private Date createTime;
	//修改时间
	private Date modifyTime;
	//是否超时
	//private Boolean isOverTime;
	//是否已经填写下一条数据
	//private boolean hasDealed;
	//下一条填写日期
	//private Date hasDealDate;
	//判断是不是第一次添加，默认为1，2为是第一次添加
	//private Integer fristAddStatus;
	//阅读状态
	private Integer readStatus;
	//回访类型：1、日常关系维护；2、普通邀约到店（邀约客户到店看车）；3、活动邀约到店
	private Integer trackType;
	//邀约活动 反馈结果 1、接受；2、待定；3、拒绝
	private Integer turnBackResult;
	//市场活动
	private CustMarketingAct custMarketingAct;
	//销售经理批阅记录
	private String salesManager;
	private Date salesDate;
	private String salesNote;
	//销售经理状态
	private Integer salesReadStatus;
	
    //客户超时统计类型：I类，客户等级：H、A、B、C级 需统计超时I;客户超时等级II：F、O、L级  无需统计超时II
	private Integer customerPhaseType;
	
	//1、创建客户创建任务；	2、客户回访创建任务；	3、流失客户转登记客户创建任务；	4、订单客户流失创建任务；5、其他情况创建
	private Integer taskCreateType;
	//1、为默认状态，2、正常回访关闭任务；	3、提报订单关闭任务；4、客户流失关闭任务；
	private Integer taskFinishType;
	//任务创建日期
	private Date taskCreateTime;
	//任务状态，1、未处理；2、已经处理；3、认为关闭
	private Integer taskDealStatus;
	//任务超时状态 1、正常未超时；2、已经超时
	private  Integer taskOverTimeStatus;
	//任务超时次数，默认为0
	private Integer taskOverTimeNum;
	//任务类型，1、次日回访；2、跟踪回访
	private Integer taskType;
	
	/////////////////////任务超时相关判断条件///////////////////////////
	//任务关闭时间;正常回访关闭时间为任务处理时间，提报订单、客户流失关闭任务时间为订单提报时间、客户流失时间.
	private Date finishDate;
	//任务超时考核状态，1、为正常。2、异常（H->O,C->L)已经超时，数据处理
	private Integer taskOverTimeAssementState;
	
	
	//到期回访日和当前日期只差 不需要记录入数据库 nextReservationTime-now
	private Integer dayNum;
	public CustomerTrack() {
	}

	public CustomerTrack(Customer customer, Date trackDate,
			Integer trackMethod, String trackContent, String result,
			String feedBackResult, String dealMethod, Integer customerPhase,
			Date nextReservationTime, String showroomManagerSuggested) {
		this.customer = customer;
		this.trackDate = trackDate;
		this.trackMethod = trackMethod;
		this.trackContent = trackContent;
		this.result = result;
		this.feedBackResult = feedBackResult;
		this.dealMethod = dealMethod;
		this.nextReservationTime = nextReservationTime;
		this.showroomManagerSuggested = showroomManagerSuggested;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getTrackDate() {
		return this.trackDate;
	}

	public void setTrackDate(Date trackDate) {
		this.trackDate = trackDate;
	}

	public Integer getTrackMethod() {
		return this.trackMethod;
	}

	public void setTrackMethod(Integer trackMethod) {
		this.trackMethod = trackMethod;
	}

	public String getTrackContent() {
		return this.trackContent;
	}

	public void setTrackContent(String trackContent) {
		this.trackContent = trackContent;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getFeedBackResult() {
		return this.feedBackResult;
	}

	public void setFeedBackResult(String feedBackResult) {
		this.feedBackResult = feedBackResult;
	}

	public String getDealMethod() {
		return this.dealMethod;
	}

	public void setDealMethod(String dealMethod) {
		this.dealMethod = dealMethod;
	}


	public CustomerPhase getBeforeCustomerPhase() {
		return beforeCustomerPhase;
	}

	public void setBeforeCustomerPhase(CustomerPhase beforeCustomerPhase) {
		this.beforeCustomerPhase = beforeCustomerPhase;
	}

	public CustomerPhase getAfterCustomerPhase() {
		return afterCustomerPhase;
	}

	public void setAfterCustomerPhase(CustomerPhase afterCustomerPhase) {
		this.afterCustomerPhase = afterCustomerPhase;
	}

	public Date getNextReservationTime() {
		return this.nextReservationTime;
	}

	public void setNextReservationTime(Date nextReservationTime) {
		this.nextReservationTime = nextReservationTime;
	}

	public String getShowroomManagerSuggested() {
		return this.showroomManagerSuggested;
	}

	public void setShowroomManagerSuggested(String showroomManagerSuggested) {
		this.showroomManagerSuggested = showroomManagerSuggested;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getReadStatus() {
		return readStatus;
	}

	public void setReadStatus(Integer readStatus) {
		this.readStatus = readStatus;
	}


	public Integer getTaskCreateType() {
		return taskCreateType;
	}

	public void setTaskCreateType(Integer taskCreateType) {
		this.taskCreateType = taskCreateType;
	}

	public Integer getTaskFinishType() {
		return taskFinishType;
	}

	public void setTaskFinishType(Integer taskFinishType) {
		this.taskFinishType = taskFinishType;
	}

	public Date getTaskCreateTime() {
		return taskCreateTime;
	}

	public void setTaskCreateTime(Date taskCreateTime) {
		this.taskCreateTime = taskCreateTime;
	}



	public Integer getTaskDealStatus() {
		return taskDealStatus;
	}

	public void setTaskDealStatus(Integer taskDealStatus) {
		this.taskDealStatus = taskDealStatus;
	}

	public Integer getTaskOverTimeStatus() {
		return taskOverTimeStatus;
	}

	public void setTaskOverTimeStatus(Integer taskOverTimeStatus) {
		this.taskOverTimeStatus = taskOverTimeStatus;
	}

	public Integer getTaskOverTimeAssementState() {
		return taskOverTimeAssementState;
	}

	public void setTaskOverTimeAssementState(Integer taskOverTimeAssementState) {
		this.taskOverTimeAssementState = taskOverTimeAssementState;
	}

	public Integer getTaskOverTimeNum() {
		return taskOverTimeNum;
	}

	public void setTaskOverTimeNum(Integer taskOverTimeNum) {
		this.taskOverTimeNum = taskOverTimeNum;
	}

	public Integer getTaskType() {
		return taskType;
	}

	public void setTaskType(Integer taskType) {
		this.taskType = taskType;
	}

	public Date getFinishDate() {
		return finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Integer getDayNum() {
		return dayNum;
	}

	public void setDayNum(Integer dayNum) {
		this.dayNum = dayNum;
	}

	public Integer getCustomerPhaseType() {
		return customerPhaseType;
	}

	public void setCustomerPhaseType(Integer customerPhaseType) {
		this.customerPhaseType = customerPhaseType;
	}

	public Integer getTrackType() {
		return trackType;
	}

	public void setTrackType(Integer trackType) {
		this.trackType = trackType;
	}

	public Integer getTurnBackResult() {
		return turnBackResult;
	}

	public void setTurnBackResult(Integer turnBackResult) {
		this.turnBackResult = turnBackResult;
	}

	public CustMarketingAct getCustMarketingAct() {
		return custMarketingAct;
	}

	public void setCustMarketingAct(CustMarketingAct custMarketingAct) {
		this.custMarketingAct = custMarketingAct;
	}

	public String getSalesManager() {
		return salesManager;
	}

	public void setSalesManager(String salesManager) {
		this.salesManager = salesManager;
	}

	public Date getSalesDate() {
		return salesDate;
	}

	public void setSalesDate(Date salesDate) {
		this.salesDate = salesDate;
	}

	public String getSalesNote() {
		return salesNote;
	}

	public void setSalesNote(String salesNote) {
		this.salesNote = salesNote;
	}

	public Integer getSalesReadStatus() {
		return salesReadStatus;
	}

	public void setSalesReadStatus(Integer salesReadStatus) {
		this.salesReadStatus = salesReadStatus;
	}
	
}
