package com.ystech.cust.model;

// Generated 2015-8-12 10:10:40 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Customerimage generated by hbm2java
 */
public class CustomerImage implements java.io.Serializable {
	public static int TYPEHANDCAR=1;
	public static int TYPEDRINGFRONT=2;
	private Integer dbid;
	private Customer customer;
	private String title;
	private String url;
	private String dis;
	private String mediaId;
	private Date createDate;
	//照片类型，1、为交车照片，2、行驶证正面照片；
	private Integer type;
	private CustomerImageApproval customerImageApproval;
	public CustomerImage() {
	}

	public CustomerImage(Integer customerId, String title, String url,
			String dis, Date createDate) {
		this.title = title;
		this.url = url;
		this.dis = dis;
		this.createDate = createDate;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDis() {
		return this.dis;
	}

	public void setDis(String dis) {
		this.dis = dis;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getMediaId() {
		return mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}
	
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public CustomerImageApproval getCustomerImageApproval() {
		return customerImageApproval;
	}

	public void setCustomerImageApproval(CustomerImageApproval customerImageApproval) {
		this.customerImageApproval = customerImageApproval;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
}
