package com.ystech.cust.model;

// Generated 2014-2-18 19:48:26 by Hibernate Tools 4.0.0

/**
 * Marital generated by hbm2java
 */
public class CustomerPhase implements java.io.Serializable {
	public static Integer LEVELO=1;
	public static Integer LEVELH=2;
	public static Integer LEVELA=3;
	public static Integer LEVELB=4;
	public static Integer LEVELC=5;
	public static Integer LEVELL=6;
	public static Integer LEVELF=7;
	//类型，1、显示下拉选择；2、系统自动跳转
	public static Integer TYPESHOW=1;
	public static Integer TYPEHIDEN=2;
	private Integer dbid;
	//名称
	private String name;
	//回访周期
	private Integer trackDay;
	//类型，1、显示下拉选择；2、系统自动跳转
	private Integer type;
	//是否进行回访提示；1、不进行提示；2、进行
	private Integer warmStatus;
	//备注
	private String note;
	//统计数据
	private Integer totalNum;

	public CustomerPhase() {
	}

	public CustomerPhase(String name, String note) {
		this.name = name;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getTrackDay() {
		return trackDay;
	}

	public void setTrackDay(Integer trackDay) {
		this.trackDay = trackDay;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getWarmStatus() {
		return warmStatus;
	}

	public void setWarmStatus(Integer warmStatus) {
		this.warmStatus = warmStatus;
	}

	public Integer getTotalNum() {
		return totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}
	
}
