package com.ystech.cust.model;

import java.util.Date;

import com.ystech.xwqr.set.model.Brand;
import com.ystech.xwqr.set.model.CarColor;
import com.ystech.xwqr.set.model.CarModel;
import com.ystech.xwqr.set.model.CarSeriy;

// Generated 2014-2-25 9:44:50 by Hibernate Tools 4.0.0

/**
 * 客户最总结果信息表
 * Customerlastbussi generated by hbm2java
 */
public class CustomerLastBussi implements java.io.Serializable {
	//0、等待审批
	public static final Integer APPROVALWATING=0;
	//1、审批同意
	public static final Integer APPROVALAGREE=1;
	//2、审批驳回
	public static final Integer APPROVALRETURN=2;
	private Integer dbid;
	private Brand brand;
	private CarModel carModel;
	private CarSeriy carSeriy;
	private CarColor carColor;
	private Boolean isCarPlate;
	private String carPlateNo;
	private Boolean isBuySafe;
	private Boolean isBoutique;
	private Customer customer;
	private String note;
	private Date createTime;
	//审批状态0、等待审批；1、审批同意；2、审批驳回 系统操作：销售副总审批同意时将修改custome为对应的结果状态的销售状态信息，驳回是customer返回初始状态。
	private Integer approvalStatus;
	private Integer approvalPersonId;
	private String approvalPersonName;
	private Date approvalDate;
	private CustomerFlowReason customerFlowReason;
	public CustomerLastBussi() {
	}

	public CustomerLastBussi(int dbid) {
		this.dbid = dbid;
	}

	public CustomerLastBussi(int dbid, Integer lastResult,
			Integer lastBuyCarModel, String carColor, String vinCode,
			Boolean isCarPlate, String carPlateNo, Boolean isBuySafe,
			Boolean isBoutique, Integer customerId, String note) {
		this.dbid = dbid;
		this.isCarPlate = isCarPlate;
		this.carPlateNo = carPlateNo;
		this.isBuySafe = isBuySafe;
		this.isBoutique = isBoutique;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public CarColor getCarColor() {
		return carColor;
	}

	public void setCarColor(CarColor carColor) {
		this.carColor = carColor;
	}

	public Boolean getIsCarPlate() {
		return this.isCarPlate;
	}

	public void setIsCarPlate(Boolean isCarPlate) {
		this.isCarPlate = isCarPlate;
	}

	public String getCarPlateNo() {
		return this.carPlateNo;
	}

	public void setCarPlateNo(String carPlateNo) {
		this.carPlateNo = carPlateNo;
	}

	public Boolean getIsBuySafe() {
		return this.isBuySafe;
	}

	public void setIsBuySafe(Boolean isBuySafe) {
		this.isBuySafe = isBuySafe;
	}

	public Boolean getIsBoutique() {
		return this.isBoutique;
	}

	public void setIsBoutique(Boolean isBoutique) {
		this.isBoutique = isBoutique;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public CarModel getCarModel() {
		return carModel;
	}

	public void setCarModel(CarModel carModel) {
		this.carModel = carModel;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getApprovalStatus() {
		return approvalStatus;
	}

	public void setApprovalStatus(Integer approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public CarSeriy getCarSeriy() {
		return carSeriy;
	}

	public void setCarSeriy(CarSeriy carSeriy) {
		this.carSeriy = carSeriy;
	}

	public Integer getApprovalPersonId() {
		return approvalPersonId;
	}

	public void setApprovalPersonId(Integer approvalPersonId) {
		this.approvalPersonId = approvalPersonId;
	}

	public String getApprovalPersonName() {
		return approvalPersonName;
	}

	public void setApprovalPersonName(String approvalPersonName) {
		this.approvalPersonName = approvalPersonName;
	}

	public Date getApprovalDate() {
		return approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public CustomerFlowReason getCustomerFlowReason() {
		return customerFlowReason;
	}

	public void setCustomerFlowReason(CustomerFlowReason customerFlowReason) {
		this.customerFlowReason = customerFlowReason;
	}
	

}
