package com.ystech.cust.model;

import java.util.Date;

// Generated 2016-10-15 16:44:26 by Hibernate Tools 4.0.0

/**
 * Customerinfrom generated by hbm2java
 * 功能描述：线索来源
 */
public class CustomerType implements java.io.Serializable {

	private Integer dbid;
	//来源名称
	private String name;
	//备注
	private String note;
	//排序
	private Integer num;
	private Date createTime;
	private Date modifyTime;

	public CustomerType() {
	}

	public CustomerType(String name, String note, Integer num,
			Integer parentId, Integer levelNum) {
		this.name = name;
		this.note = note;
		this.num = num;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}



}
