package com.ystech.cust.model;

// Generated 2016-10-8 12:01:13 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customerrecordtarget generated by hbm2java
 */
public class CustomerRecordClubInvalidReason implements java.io.Serializable {
	//类型 进店 1
	public static int TYPECOMIN=1;
	//类型 来电 2
	public static int TYPEPHONE=2;
	private Integer dbid;
	private Integer type;
	private String name;
	private String note;
	private Integer num;
	private Date createDate;
	private Date modifyDate;
	private Set customerrecords = new HashSet(0);

	public CustomerRecordClubInvalidReason() {
	}

	public CustomerRecordClubInvalidReason(Integer type, String name, String note,
			Integer num, Date createDate, Date modifyDate, Set customerrecords) {
		this.type = type;
		this.name = name;
		this.note = note;
		this.num = num;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.customerrecords = customerrecords;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Set getCustomerrecords() {
		return this.customerrecords;
	}

	public void setCustomerrecords(Set customerrecords) {
		this.customerrecords = customerrecords;
	}

}
