package com.ystech.cust.model;

import com.ystech.xwqr.set.model.Brand;

// Generated 2014-8-16 10:45:55 by Hibernate Tools 4.0.0

/**
 * Distributorbrand generated by hbm2java
 */
public class DistributorBrand implements java.io.Serializable {

	private Integer dbid;
	private Brand brand;
	private String brandName;
	private String contactName;
	private String mobilePhone;
	private String phone;
	private String address;
	private String note;
	private Integer distributorId;

	public DistributorBrand() {
	}

	public DistributorBrand(Integer brandId, String brandName,
			String contactName, String mobilePhone, String phone,
			String address, String note, Integer distributorId) {
		this.brandName = brandName;
		this.contactName = contactName;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.address = address;
		this.note = note;
		this.distributorId = distributorId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getDistributorId() {
		return this.distributorId;
	}

	public void setDistributorId(Integer distributorId) {
		this.distributorId = distributorId;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

}
