package com.ystech.cust.model;
// Generated 2014-8-16 10:45:55 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Distributorchargeperson generated by hbm2java
 */
public class DistributorChargePerson  implements java.io.Serializable {


     private Integer dbid;
     private Integer distributorId;
     private String name;
     private String mobilePhone;
     private String phone;
     private String icard;
     private Date birthDay;
     private String address;
     private String note;

    public DistributorChargePerson() {
    }

    public DistributorChargePerson(Integer distributorId, String name, String mobilePhone, String phone, String icard, Date birthDay, String address) {
       this.distributorId = distributorId;
       this.name = name;
       this.mobilePhone = mobilePhone;
       this.phone = phone;
       this.icard = icard;
       this.birthDay = birthDay;
       this.address = address;
    }
   
    public Integer getDbid() {
        return this.dbid;
    }
    
    public void setDbid(Integer dbid) {
        this.dbid = dbid;
    }
    public Integer getDistributorId() {
        return this.distributorId;
    }
    
    public void setDistributorId(Integer distributorId) {
        this.distributorId = distributorId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getIcard() {
        return this.icard;
    }
    
    public void setIcard(String icard) {
        this.icard = icard;
    }
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}


