package com.ystech.cust.model;

// Generated 2014-8-16 10:45:55 by Hibernate Tools 4.0.0

/**
 * Distributorsuboutlet generated by hbm2java
 */
public class DistributorSuboutlet implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String address;
	private String contactPerson;
	private String mobilePhone;
	private String phone;
	private String otherBrand;
	private String note;
	private Integer distributorId;

	public DistributorSuboutlet() {
	}

	public DistributorSuboutlet(String name, String address,
			String contactPerson, String mobilePhone, String phone,
			String otherBrand, String note, Integer distributorId) {
		this.name = name;
		this.address = address;
		this.contactPerson = contactPerson;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.otherBrand = otherBrand;
		this.note = note;
		this.distributorId = distributorId;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getOtherBrand() {
		return this.otherBrand;
	}

	public void setOtherBrand(String otherBrand) {
		this.otherBrand = otherBrand;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getDistributorId() {
		return this.distributorId;
	}

	public void setDistributorId(Integer distributorId) {
		this.distributorId = distributorId;
	}

}
