package com.ystech.cust.model;

// Generated 2014-8-16 9:34:23 by Hibernate Tools 4.0.0

/**
 * Distributortype generated by hbm2java
 */
public class DistributorType implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String note;
	private Integer companyId;

	public DistributorType() {
	}

	public DistributorType(String name, String note) {
		this.name = name;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	

}
