package com.ystech.cust.model;

// Generated 2014-7-10 19:24:23 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Fiwaresult generated by hbm2java
 */
public class Fiwaresult implements java.io.Serializable {

	private Integer dbid;
	private Integer dg;
	private Integer agt;
	private Date createTime;

	public Fiwaresult() {
	}

	public Fiwaresult(Integer dg, Integer agt, Date createTime) {
		this.dg = dg;
		this.agt = agt;
		this.createTime = createTime;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getDg() {
		return this.dg;
	}

	public void setDg(Integer dg) {
		this.dg = dg;
	}

	public Integer getAgt() {
		return this.agt;
	}

	public void setAgt(Integer agt) {
		this.agt = agt;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
