package com.ystech.cust.model;

import java.util.Date;

// Generated 2014-7-10 19:01:50 by Hibernate Tools 4.0.0

/**
 * Fiwa generated by hbm2java
 */
public class Fiwa implements java.io.Serializable {
	//默认
	public static Integer DEFAULT=0;
	//胜利
	public static Integer WIN=1;
	//失败
	public static Integer LOSE=2;
	
	private Integer dbid;
	//德国
	private Integer dg;
	//阿根廷
	private Integer agt;
	//客户名称
	private String name;
	//联系电话
	private String mobile;
	//选择奖品
	private Integer jp;
	//默认等待开奖、失败、获取
	private Integer isWin;
	private Date createDate;
	private Date modifyDate;
	public Fiwa() {
	}


	public Fiwa(int dbid, Integer dg, Integer agt, String name, String mobile,
			Integer jp, Integer isWin) {
		this.dg = dg;
		this.agt = agt;
		this.name = name;
		this.mobile = mobile;
		this.jp = jp;
		this.isWin = isWin;
	}


	public Integer getDg() {
		return this.dg;
	}

	public void setDg(Integer dg) {
		this.dg = dg;
	}

	public Integer getAgt() {
		return this.agt;
	}

	public void setAgt(Integer agt) {
		this.agt = agt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getJp() {
		return this.jp;
	}

	public void setJp(Integer jp) {
		this.jp = jp;
	}

	public Integer getIsWin() {
		return this.isWin;
	}

	public void setIsWin(Integer isWin) {
		this.isWin = isWin;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getDbid() {
		return dbid;
	}

}
