package com.ystech.cust.model;

// Generated 2014-2-18 21:01:08 by Hibernate Tools 4.0.0

/**
 * Constellation generated by hbm2java
 */
public class InfoFromTotal implements java.io.Serializable {

	private Integer dbid;
	private Integer totalCount;
	private Double per;
	private String inName;

	public InfoFromTotal() {
	}

	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getTotalCount() {
		return totalCount;
	}

	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	public Double getPer() {
		return per;
	}

	public void setPer(Double per) {
		this.per = per;
	}

	public String getInName() {
		return inName;
	}

	public void setInName(String inName) {
		this.inName = inName;
	}


}
