package com.ystech.cust.model;

// Generated 2015-1-9 15:36:47 by Hibernate Tools 4.0.0

/**
 * Ordercontractexpenseschargeitem generated by hbm2java
 */
public class OrderContractExpensesChargeItem implements java.io.Serializable {

	private Integer dbid;
	private OrderContractExpenses ordercontractexpenses;
	private Integer chargeItemId;
	private String chargeItemName;
	private Double price;
	private Double costPrice;
	private String note;

	public OrderContractExpensesChargeItem() {
	}

	public OrderContractExpensesChargeItem(int dbid) {
		this.dbid = dbid;
	}

	public OrderContractExpensesChargeItem(int dbid,
			OrderContractExpenses ordercontractexpenses, Integer chargeItemId,
			String chargeItemName, Double price, String note) {
		this.dbid = dbid;
		this.ordercontractexpenses = ordercontractexpenses;
		this.chargeItemId = chargeItemId;
		this.chargeItemName = chargeItemName;
		this.price = price;
		this.note = note;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public OrderContractExpenses getOrdercontractexpenses() {
		return this.ordercontractexpenses;
	}

	public void setOrdercontractexpenses(
			OrderContractExpenses ordercontractexpenses) {
		this.ordercontractexpenses = ordercontractexpenses;
	}

	public Integer getChargeItemId() {
		return this.chargeItemId;
	}

	public void setChargeItemId(Integer chargeItemId) {
		this.chargeItemId = chargeItemId;
	}

	public String getChargeItemName() {
		return this.chargeItemName;
	}

	public void setChargeItemName(String chargeItemName) {
		this.chargeItemName = chargeItemName;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Double getCostPrice() {
		return costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

}
