package com.ystech.cust.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2014-12-5 11:18:37 by Hibernate Tools 4.0.0

/**
 * Orderdecore generated by hbm2java
 */
public class OrderContractDecore implements java.io.Serializable {

	private Integer dbid;
	private OrderContract orderContract;
	//实收金额
	private Double acturePrice;
	//客户
	private Customer customer;
	//折扣率
	private String zkl;
	//赠送总额合同及
	private Double giveTotalPrice;
	//销售装饰合计
	private Double decoreSaleTotalPrce;
	//销售顾问结算价总额
	private Double salerTotalPrice;
	//销售顾问结算利润（实收总金额-销售顾问结算价）
	private Double salerGrofitPrice;
	//实际成本
	private Double costPrice;
	//实际利润
	private Double costGrofitPrice;
	
	private Set orderContractDecoreItem = new HashSet(0);
	public OrderContractDecore() {
	}

	public OrderContractDecore(Integer orderContractId, Double decoreSaleTotalPrce,
			Double acturePrice, Double zkl, Double giveTotalPrice) {
		this.decoreSaleTotalPrce = decoreSaleTotalPrce;
		this.acturePrice = acturePrice;
		this.giveTotalPrice = giveTotalPrice;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public OrderContract getOrderContract() {
		return orderContract;
	}

	public void setOrderContract(OrderContract orderContract) {
		this.orderContract = orderContract;
	}

	public Double getDecoreSaleTotalPrce() {
		return this.decoreSaleTotalPrce;
	}

	public void setDecoreSaleTotalPrce(Double decoreSaleTotalPrce) {
		this.decoreSaleTotalPrce = decoreSaleTotalPrce;
	}

	public Double getActurePrice() {
		return this.acturePrice;
	}

	public void setActurePrice(Double acturePrice) {
		this.acturePrice = acturePrice;
	}

	public String getZkl() {
		return this.zkl;
	}

	public void setZkl(String zkl) {
		this.zkl = zkl;
	}

	public Double getGiveTotalPrice() {
		return this.giveTotalPrice;
	}

	public void setGiveTotalPrice(Double giveTotalPrice) {
		this.giveTotalPrice = giveTotalPrice;
	}

	public Set getOrderContractDecoreItem() {
		return orderContractDecoreItem;
	}

	public void setOrderContractDecoreItem(Set orderContractDecoreItem) {
		this.orderContractDecoreItem = orderContractDecoreItem;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Double getSalerTotalPrice() {
		return salerTotalPrice;
	}

	public void setSalerTotalPrice(Double salerTotalPrice) {
		this.salerTotalPrice = salerTotalPrice;
	}

	public Double getSalerGrofitPrice() {
		return salerGrofitPrice;
	}

	public void setSalerGrofitPrice(Double salerGrofitPrice) {
		this.salerGrofitPrice = salerGrofitPrice;
	}

	public Double getCostPrice() {
		return costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

	public Double getCostGrofitPrice() {
		return costGrofitPrice;
	}

	public void setCostGrofitPrice(Double costGrofitPrice) {
		this.costGrofitPrice = costGrofitPrice;
	}
	
}
