package com.ystech.cust.model;

// Generated 2015-1-9 15:36:47 by Hibernate Tools 4.0.0

/**
 * Ordercontractexpensespreferenceitem generated by hbm2java
 */
public class OrderContractExpensesPreferenceItem implements
		java.io.Serializable {

	private Integer dbid;
	private OrderContractExpenses ordercontractexpenses;
	private String preferenceItemName;
	private Double price;
	private String note;
	private Integer preferenceItemId;

	public OrderContractExpensesPreferenceItem() {
	}

	public OrderContractExpensesPreferenceItem(int dbid) {
		this.dbid = dbid;
	}

	public OrderContractExpensesPreferenceItem(int dbid,
			OrderContractExpenses ordercontractexpenses,
			String preferenceItemName, Double price, String note,
			Integer orderContractExpensesId) {
		this.dbid = dbid;
		this.ordercontractexpenses = ordercontractexpenses;
		this.preferenceItemName = preferenceItemName;
		this.price = price;
		this.note = note;
	}


	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public OrderContractExpenses getOrdercontractexpenses() {
		return this.ordercontractexpenses;
	}

	public void setOrdercontractexpenses(
			OrderContractExpenses ordercontractexpenses) {
		this.ordercontractexpenses = ordercontractexpenses;
	}

	public String getPreferenceItemName() {
		return this.preferenceItemName;
	}

	public void setPreferenceItemName(String preferenceItemName) {
		this.preferenceItemName = preferenceItemName;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getPreferenceItemId() {
		return preferenceItemId;
	}

	public void setPreferenceItemId(Integer preferenceItemId) {
		this.preferenceItemId = preferenceItemId;
	}


}
