package com.ystech.cust.model;

// Generated 2014-3-11 9:08:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 合同订单管理
 * Ordercontract generated by hbm2java
 */
	//合同订单创建填写完成（分为两个小步骤：第一填写订单；第二填写装饰单：）
public class OrderContract implements java.io.Serializable {
	//创建订单未填写装饰单
	public static final Integer WATINGDECORE=0;
	//等待审批,审批中
	public static final Integer STATUSWATING=1;
	//审批通过
	public static final Integer STATUSYEAS=2;
	//审批驳回
	public static final Integer STATUSNO=3;
	//已经打印合同
	public static final Integer PRINT=4;
	private Integer dbid;
	private String name;
	private String contactPhone;
	private String address;
	private String zipCode;
	private String icard;
	private String bank;
	private String bankNo;
	private BigDecimal orderMoney;
	private String bigOrderMoney;
	private String handerOverCarDate;
	private String note;
	private String additionalNote;
	private String needRepresentative;
	private Integer status;
	private Customer customer;
	private String salesRepresentative;
	private String showRoomManager;
	private Date createTime;
	private Date modifyTime;
	private Boolean isShowNote;
	//2014年11月15日添加
	//合同总金额
	private Double totalPrice;
	private Set ordercontractproducts = new HashSet(0);
	private OrderContractExpenses orderContractExpenses;
	public OrderContract() {
	}

	public OrderContract(String name, String contactPhone, String address,
			String zipCode, String bank, String bankNo, Long orderMoney,
			String handerOverCarDate, String note, String needRepresentative,
			Integer status, Integer customerId, Set ordercontractproducts) {
		this.name = name;
		this.contactPhone = contactPhone;
		this.address = address;
		this.zipCode = zipCode;
		this.bank = bank;
		this.bankNo = bankNo;
		this.handerOverCarDate = handerOverCarDate;
		this.note = note;
		this.needRepresentative = needRepresentative;
		this.status = status;
		this.ordercontractproducts = ordercontractproducts;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public BigDecimal getOrderMoney() {
		return this.orderMoney;
	}

	public void setOrderMoney(BigDecimal orderMoney) {
		this.orderMoney = orderMoney;
	}

	public String getHanderOverCarDate() {
		return this.handerOverCarDate;
	}

	public void setHanderOverCarDate(String handerOverCarDate) {
		this.handerOverCarDate = handerOverCarDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getNeedRepresentative() {
		return this.needRepresentative;
	}

	public void setNeedRepresentative(String needRepresentative) {
		this.needRepresentative = needRepresentative;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}


	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getBigOrderMoney() {
		return bigOrderMoney;
	}

	public void setBigOrderMoney(String bigOrderMoney) {
		this.bigOrderMoney = bigOrderMoney;
	}

	public Set getOrdercontractproducts() {
		return this.ordercontractproducts;
	}

	public void setOrdercontractproducts(Set ordercontractproducts) {
		this.ordercontractproducts = ordercontractproducts;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getSalesRepresentative() {
		return salesRepresentative;
	}

	public void setSalesRepresentative(String salesRepresentative) {
		this.salesRepresentative = salesRepresentative;
	}

	public String getShowRoomManager() {
		return showRoomManager;
	}

	public void setShowRoomManager(String showRoomManager) {
		this.showRoomManager = showRoomManager;
	}

	public String getIcard() {
		return icard;
	}

	public void setIcard(String icard) {
		this.icard = icard;
	}

	public Boolean getIsShowNote() {
		return isShowNote;
	}

	public void setIsShowNote(Boolean isShowNote) {
		this.isShowNote = isShowNote;
	}


	public Double getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getAdditionalNote() {
		return additionalNote;
	}

	public void setAdditionalNote(String additionalNote) {
		this.additionalNote = additionalNote;
	}

	public OrderContractExpenses getOrderContractExpenses() {
		return orderContractExpenses;
	}

	public void setOrderContractExpenses(OrderContractExpenses orderContractExpenses) {
		this.orderContractExpenses = orderContractExpenses;
	}
	
	
}
