package com.ystech.cust.model;

import java.math.BigDecimal;

import com.ystech.xwqr.set.model.CarColor;
import com.ystech.xwqr.set.model.CarModel;
import com.ystech.xwqr.set.model.CarSeriy;

// Generated 2014-3-11 9:08:47 by Hibernate Tools 4.0.0

/**
 * Ordercontractproduct generated by hbm2java
 */
public class OrderContractProduct implements java.io.Serializable {

	private Integer dbid;
	private OrderContract ordercontract;
	private CarSeriy carseriy;
	private CarModel carModel;
	private CarColor carColor;
	private BigDecimal price;
	private String num;
	private String note;

	public OrderContractProduct() {
	}

	public OrderContractProduct(OrderContract ordercontract,
			Integer carseriyId, Integer carModelId, String color, BigDecimal price,
			Integer num, String note) {
		this.ordercontract = ordercontract;
		this.price = price;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public OrderContract getOrdercontract() {
		return this.ordercontract;
	}

	public void setOrdercontract(OrderContract ordercontract) {
		this.ordercontract = ordercontract;
	}


	public CarSeriy getCarseriy() {
		return carseriy;
	}

	public void setCarseriy(CarSeriy carseriy) {
		this.carseriy = carseriy;
	}

	public CarModel getCarModel() {
		return carModel;
	}

	public void setCarModel(CarModel carModel) {
		this.carModel = carModel;
	}



	public CarColor getCarColor() {
		return carColor;
	}

	public void setCarColor(CarColor carColor) {
		this.carColor = carColor;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}


	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
