package com.ystech.cust.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ystech.xwqr.set.model.CarSeriy;

// Generated 2014-2-20 10:08:44 by Hibernate Tools 4.0.0

/**
 * 1、商品信息表
 * 2、套餐表公用
 * 3、单独的管理实体
 * 4、销售员查询添加附加通知单选择套餐或商品
 * 5、物流部添加装饰应用
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {
	public static final Integer TYPEPRODCUT=1; 
	public static final Integer TYPEPACKAGE=2; 
	public static final Integer STOCKSTATUSCOMM=1; 
	public static final Integer STOCKSTATUSMAX=2; 
	public static final Integer STOCKSTATUSMIN=3; 
	//商品启用状态
	public static final Integer STOPCOMM=1; 
	public static final Integer STOPYEAS=2; 
	
	
	private Integer dbid;
	//产品品类型
	private ProductCategory productcategory;
	//编码
	private String sn;
	//名称
	private String name;
	//品牌
	private String brandIds;
	//品牌名称
	private String brandNames;
	//价格
	private BigDecimal price;
	//市场价格
	private BigDecimal costPrice;
	//施工成本
	private BigDecimal constructCostPrice;
	//折扣
	private Float discount;
	//单位
	private String unit;
	//规格
	private String specification;
	//是否启用库存
	private Boolean isStock;
	//是否跟踪
	private Boolean isTrack;
	//更正周期
	private Integer trackTimeLong;
	//库存数量
	private Integer stockNum;
	//是否提成
	private Boolean isDeductPercentage;
	//提成比例
	private Float deductPercert;
	//是否礼品
	private Boolean isGift;
	//扣除积分
	private Integer deductionScore;
	//
	private Integer  integral;
	//备注
	private String note;
	//拼音
	private String pingyin;
	//商家ID
	private Integer enterpriseId;
	private Date createTime;
	private Date modifyTime;

	//标示数据为商品还是套餐1为商品，2为套餐
	private Integer type;
	//车系
	private CarSeriy carSeriy;
	//套餐Ids
	private String packageIds;
	//套餐商品明细
	private String packageDetail;
	//销售顾问结算价
	private BigDecimal salerCostPrice;
	private Integer maxStockNum;
	private Integer minStockNum;
	private Integer startStockNum;
	private Integer stockStatus;
	//商品停用状态：2、为停用，1、为启用
	private Integer stopStatus;
	//适用类型(1、为通用、2、为共用）
	private Integer commType;
	private String enterpriseIds;
	public Product() {
	}

	public Product(Integer dbid) {
		this.dbid = dbid;
	}

	public Product(int dbid, ProductCategory productcategory, String sn,
			String name, Integer brandId, Double price, Double costPrice,
			Float discount, String unit, String specification, Boolean isStock,
			Boolean isTrack, Integer trackTimeLong, Integer stockNum,
			Boolean isDeductPercentage, Float deductPercert, Boolean isGift,
			Integer deductionScore, String note) {
		this.dbid = dbid;
		this.productcategory = productcategory;
		this.sn = sn;
		this.name = name;
		this.discount = discount;
		this.unit = unit;
		this.specification = specification;
		this.isStock = isStock;
		this.isTrack = isTrack;
		this.trackTimeLong = trackTimeLong;
		this.stockNum = stockNum;
		this.isDeductPercentage = isDeductPercentage;
		this.deductPercert = deductPercert;
		this.isGift = isGift;
		this.deductionScore = deductionScore;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public ProductCategory getProductcategory() {
		return this.productcategory;
	}

	public void setProductcategory(ProductCategory productcategory) {
		this.productcategory = productcategory;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getBrandIds() {
		return brandIds;
	}

	public void setBrandIds(String brandIds) {
		this.brandIds = brandIds;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getCostPrice() {
		return costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	public Float getDiscount() {
		return this.discount;
	}

	public void setDiscount(Float discount) {
		this.discount = discount;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getSpecification() {
		return this.specification;
	}

	public void setSpecification(String specification) {
		this.specification = specification;
	}

	public Boolean getIsStock() {
		return this.isStock;
	}

	public void setIsStock(Boolean isStock) {
		this.isStock = isStock;
	}

	public Boolean getIsTrack() {
		return this.isTrack;
	}

	public void setIsTrack(Boolean isTrack) {
		this.isTrack = isTrack;
	}

	public Integer getTrackTimeLong() {
		return this.trackTimeLong;
	}

	public void setTrackTimeLong(Integer trackTimeLong) {
		this.trackTimeLong = trackTimeLong;
	}



	public Boolean getIsDeductPercentage() {
		return this.isDeductPercentage;
	}

	public void setIsDeductPercentage(Boolean isDeductPercentage) {
		this.isDeductPercentage = isDeductPercentage;
	}

	public Float getDeductPercert() {
		return this.deductPercert;
	}

	public void setDeductPercert(Float deductPercert) {
		this.deductPercert = deductPercert;
	}

	public Boolean getIsGift() {
		return this.isGift;
	}

	public void setIsGift(Boolean isGift) {
		this.isGift = isGift;
	}

	public Integer getDeductionScore() {
		return this.deductionScore;
	}

	public void setDeductionScore(Integer deductionScore) {
		this.deductionScore = deductionScore;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getIntegral() {
		return integral;
	}

	public void setIntegral(Integer integral) {
		this.integral = integral;
	}

	public Integer getStockNum() {
		return stockNum;
	}

	public void setStockNum(Integer stockNum) {
		this.stockNum = stockNum;
	}

	public String getPingyin() {
		return pingyin;
	}

	public void setPingyin(String pingyin) {
		this.pingyin = pingyin;
	}

	public CarSeriy getCarSeriy() {
		return carSeriy;
	}

	public void setCarSeriy(CarSeriy carSeriy) {
		this.carSeriy = carSeriy;
	}

	public String getPackageIds() {
		return packageIds;
	}

	public void setPackageIds(String packageIds) {
		this.packageIds = packageIds;
	}

	public String getPackageDetail() {
		return packageDetail;
	}

	public void setPackageDetail(String packageDetail) {
		this.packageDetail = packageDetail;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public BigDecimal getSalerCostPrice() {
		return salerCostPrice;
	}

	public void setSalerCostPrice(BigDecimal salerCostPrice) {
		this.salerCostPrice = salerCostPrice;
	}

	public Integer getMaxStockNum() {
		return maxStockNum;
	}

	public void setMaxStockNum(Integer maxStockNum) {
		this.maxStockNum = maxStockNum;
	}

	public Integer getMinStockNum() {
		return minStockNum;
	}

	public void setMinStockNum(Integer minStockNum) {
		this.minStockNum = minStockNum;
	}

	public Integer getStartStockNum() {
		return startStockNum;
	}

	public void setStartStockNum(Integer startStockNum) {
		this.startStockNum = startStockNum;
	}

	public Integer getStockStatus() {
		return stockStatus;
	}

	public void setStockStatus(Integer stockStatus) {
		this.stockStatus = stockStatus;
	}

	public Integer getStopStatus() {
		return stopStatus;
	}

	public void setStopStatus(Integer stopStatus) {
		this.stopStatus = stopStatus;
	}

	public BigDecimal getConstructCostPrice() {
		return constructCostPrice;
	}

	public void setConstructCostPrice(BigDecimal constructCostPrice) {
		this.constructCostPrice = constructCostPrice;
	}

	public String getEnterpriseIds() {
		return enterpriseIds;
	}

	public void setEnterpriseIds(String enterpriseIds) {
		this.enterpriseIds = enterpriseIds;
	}

	public Integer getCommType() {
		return commType;
	}

	public void setCommType(Integer commType) {
		this.commType = commType;
	}

	public String getBrandNames() {
		return brandNames;
	}

	public void setBrandNames(String brandNames) {
		this.brandNames = brandNames;
	}
	

}
