package com.ystech.cust.model;

// Generated 2014-2-20 10:08:44 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productcategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private Integer orderNum;
	private Date createTime;
	private Date modifyTime;
	private ProductCategory parent;
	private Integer enterpriseId;
	private String note;
	private Set products = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(String name, Integer orderNum, Date createTime,
			Date modifyTime, Integer parentId, String note, Set products) {
		this.name = name;
		this.orderNum = orderNum;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.note = note;
		this.products = products;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public ProductCategory getParent() {
		return parent;
	}

	public void setParent(ProductCategory parent) {
		this.parent = parent;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}


}
