package com.ystech.cust.model;

// Generated 2014-7-26 17:16:01 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Smstemplate generated by hbm2java
 */
public class SmsTemplate implements java.io.Serializable {

	private Integer dbid;
	private Integer type;
	private String content;
	private String name;
	private Date createTime;
	private Date modifyTime;

	public SmsTemplate() {
	}

	public SmsTemplate(Integer type, String content, Date createTime,
			Date modifyTime) {
		this.type = type;
		this.content = content;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
