package com.ystech.cust.model;

// Generated 2014-6-28 22:58:54 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Timeoutstrackrecord generated by hbm2java
 */
public class TimeoutsTrackRecord implements java.io.Serializable {

	private Integer dbid;
	private Customer customer;
	//是否次日回访过
	private Boolean isNewlyAdd;
	//是否合同流失客户
	private Boolean isContrackReturn;
	//合同流失客户试驾
	private Date contrackReturnDate;
	//是否还原客户
	private Boolean isOutFlowReturn;
	//还原客户试驾
	private Date outFlowReturnDate;
	//次日回访超时次数
	private Integer theNextDayTimeOutNum;
	//系统实时记录追踪超时次数
	private Integer trackingTimeoutNum;
	//超时手动次数
	private Integer trackingTotalNum;
	
	public TimeoutsTrackRecord() {
	}

	public TimeoutsTrackRecord(Integer customerId, Boolean isNewlyAdd,
			Boolean isContrackReturn, Date contrackReturnDate,
			Boolean isOutFlowReturn, Date outFlowReturnDate,
			Integer theNextDayTimeOutNum, Integer trackingTimeoutNum) {
		this.isNewlyAdd = isNewlyAdd;
		this.isContrackReturn = isContrackReturn;
		this.contrackReturnDate = contrackReturnDate;
		this.isOutFlowReturn = isOutFlowReturn;
		this.outFlowReturnDate = outFlowReturnDate;
		this.theNextDayTimeOutNum = theNextDayTimeOutNum;
		this.trackingTimeoutNum = trackingTimeoutNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Boolean getIsNewlyAdd() {
		return this.isNewlyAdd;
	}

	public void setIsNewlyAdd(Boolean isNewlyAdd) {
		this.isNewlyAdd = isNewlyAdd;
	}

	public Boolean getIsContrackReturn() {
		return this.isContrackReturn;
	}

	public void setIsContrackReturn(Boolean isContrackReturn) {
		this.isContrackReturn = isContrackReturn;
	}

	public Date getContrackReturnDate() {
		return this.contrackReturnDate;
	}

	public void setContrackReturnDate(Date contrackReturnDate) {
		this.contrackReturnDate = contrackReturnDate;
	}

	public Boolean getIsOutFlowReturn() {
		return this.isOutFlowReturn;
	}

	public void setIsOutFlowReturn(Boolean isOutFlowReturn) {
		this.isOutFlowReturn = isOutFlowReturn;
	}

	public Date getOutFlowReturnDate() {
		return this.outFlowReturnDate;
	}

	public void setOutFlowReturnDate(Date outFlowReturnDate) {
		this.outFlowReturnDate = outFlowReturnDate;
	}

	public Integer getTheNextDayTimeOutNum() {
		return this.theNextDayTimeOutNum;
	}

	public void setTheNextDayTimeOutNum(Integer theNextDayTimeOutNum) {
		this.theNextDayTimeOutNum = theNextDayTimeOutNum;
	}

	public Integer getTrackingTimeoutNum() {
		return this.trackingTimeoutNum;
	}

	public void setTrackingTimeoutNum(Integer trackingTimeoutNum) {
		this.trackingTimeoutNum = trackingTimeoutNum;
	}

	public Integer getTrackingTotalNum() {
		return trackingTotalNum;
	}

	public void setTrackingTotalNum(Integer trackingTotalNum) {
		this.trackingTotalNum = trackingTotalNum;
	}

}
