package com.ystech.xwqr.model.sys;

// Generated 2013-6-2 23:21:11 by Hibernate Tools 4.0.0

/**
 * Enterprise generated by hbm2java
 */
public class Enterprise implements java.io.Serializable {
	//微信红包发送状态：1、为默认；2、可发送
	public static Integer PAYCOMM=1;
	public static Integer PAYSENDYEAS=2;
	private Integer dbid;
	private String name;
	private String phone;
	private String fax;
	private String zipCode;
	private String address;
	private String webAddress;
	private String email;
	private String bank;
	private String account;
	private String content;
	private Integer userId;
	private String allName;
	
	//试乘试驾专线
	private String tryCarPhone;
	//维修修保养
	private String maintCarPhone;
	//旧车评估
	private String oldCarPhone;
	//年审预约
	private String eaxminPhone;
	//紧急救援
	private String emergencyPhone;
	//销售电话
	private String salerPhone;
	
	//微信红包发送状态：1、为默认；2、可发送
	private Integer payStatus;
	private String point;
	//公司业务类型： 1、为小车；2、卡车业务；3、多品牌
	private Integer bussiType;

	public Enterprise() {
	}

	public Enterprise(String name, String phone, String fax, String zipCode,
			String address, String webAddress, String email, String bank,
			String account, String content) {
		this.name = name;
		this.phone = phone;
		this.fax = fax;
		this.zipCode = zipCode;
		this.address = address;
		this.webAddress = webAddress;
		this.email = email;
		this.bank = bank;
		this.account = account;
		this.content = content;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getAllName() {
		return allName;
	}

	public void setAllName(String allName) {
		this.allName = allName;
	}

	public Integer getPayStatus() {
		return payStatus;
	}

	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	public String getTryCarPhone() {
		return tryCarPhone;
	}

	public void setTryCarPhone(String tryCarPhone) {
		this.tryCarPhone = tryCarPhone;
	}

	public String getMaintCarPhone() {
		return maintCarPhone;
	}

	public void setMaintCarPhone(String maintCarPhone) {
		this.maintCarPhone = maintCarPhone;
	}

	public String getOldCarPhone() {
		return oldCarPhone;
	}

	public void setOldCarPhone(String oldCarPhone) {
		this.oldCarPhone = oldCarPhone;
	}

	public String getEaxminPhone() {
		return eaxminPhone;
	}

	public void setEaxminPhone(String eaxminPhone) {
		this.eaxminPhone = eaxminPhone;
	}

	public String getEmergencyPhone() {
		return emergencyPhone;
	}

	public void setEmergencyPhone(String emergencyPhone) {
		this.emergencyPhone = emergencyPhone;
	}

	public String getSalerPhone() {
		return salerPhone;
	}

	public void setSalerPhone(String salerPhone) {
		this.salerPhone = salerPhone;
	}

	public String getPoint() {
		return point;
	}

	public void setPoint(String point) {
		this.point = point;
	}

	public Integer getBussiType() {
		return bussiType;
	}

	public void setBussiType(Integer bussiType) {
		this.bussiType = bussiType;
	}
	

}
