package com.ystech.xwqr.model.sys;

// Generated 2015-6-18 16:17:42 by Hibernate Tools 4.0.0

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String discription;
	private Position parent;
	private Integer suqNo;

	public Position() {
	}

	public Position(String name, String discription, Integer parentId,
			Integer suqNo) {
		this.name = name;
		this.discription = discription;
		this.suqNo = suqNo;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	public Position getParent() {
		return parent;
	}

	public void setParent(Position parent) {
		this.parent = parent;
	}

	public Integer getSuqNo() {
		return this.suqNo;
	}

	public void setSuqNo(Integer suqNo) {
		this.suqNo = suqNo;
	}

}
