package com.ystech.xwqr.model.sys;


// Generated 2014-3-19 19:13:05 by Hibernate Tools 4.0.0

/**
 * Receivemessageuser generated by hbm2java
 */
public class ReceiveMessageUser implements java.io.Serializable {

	private Integer dbid;
	private User user;

	public ReceiveMessageUser() {
	}


	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}


	public User getUser() {
		return user;
	}


	public void setUser(User user) {
		this.user = user;
	}


}
