package com.ystech.xwqr.model.sys;

import java.util.Date;
import java.util.Set;

// Generated 2012-11-21 17:13:09 by Hibernate Tools 3.4.0.CR1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {
	private Integer dbid;
	private String name;//角色名称
	private Integer state;//状态
	private String note;//备注
	private Integer roleType;//角色类型：1、
	private Set<Resource> resources;
	private Set<User> users;
	//创建时间
	private Date createTime;
	//修改时间
	private Date modifyTime;
	//微信用户是否同步 1、未同步；2、已结同步
	private Integer sysWeixinStatus;
	public Role() {
	}

	public Role(String name, Integer state, String note) {
		this.name = name;
		this.state = state;
		this.note = note;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Resource> getResources() {
		return resources;
	}

	public void setResources(Set<Resource> resources) {
		this.resources = resources;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Integer getRoleType() {
		return roleType;
	}

	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getSysWeixinStatus() {
		return sysWeixinStatus;
	}

	public void setSysWeixinStatus(Integer sysWeixinStatus) {
		this.sysWeixinStatus = sysWeixinStatus;
	}
	
	
}
