package com.ystech.xwqr.model.sys;

import java.io.Serializable;
import java.util.Collection;
import java.util.Comparator;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;


// Generated 2012-11-21 17:13:09 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements UserDetails, java.io.Serializable {
	//用户微信关注状态1 默认 未关注
	public static final Integer ATTATIONSTATUSDEFUAL=1;
	//用户微信关注状态2 已经关注
	public static final Integer ATTATIONED=2;
	//用户微信关注状态2 停用
	public static final Integer ATTATONSTOP=3;
	
	//区分管理员
	public static Integer ADMINTYPEADMIN=1;
	//普通用户
	public static Integer ADMINTYPEADCOMM=2;
	//合同流失审批权限 为默认
	public static Integer APPROVALCOMM=1;
	//合同流失审批权限 拥有审批权限
	public static Integer APPROVALYES=2;
	
	//查询权限 为默认
	public static Integer QUERYCOMM=1;
	//查询权限 拥有查询权限
	public static Integer QUERYYES=2;
	
	//微信账号是否同步 为默认
	public static Integer SYNCOMM=1;
	//微信账号是否同步 拥有查询权限
	public static Integer SYNYYES=2;
	
	//领导自我审批合同 1、为默认
	public static Integer SELFAPPROVALCOMM=1;
	//领导自我审批合同 2、拥有查询权限
	public static Integer SELFAPPROVALYEAS=2;
	
	//用户类型：2、网销
	public static Integer bussiTypeNet=2;
	
	private Integer dbid;
	private String userId;
	private String realName;
	private String sex;
	private String password;
	private String email;
	private String mobilePhone;
	//微信号（扩展企业微信）
	private String wechatId;
	private String phone;
	private String qq;
	private String positionIds;
	private String positionNames;
	//单位名称
	private String companyName;
	//微信是否关注微信，1、未关注，2、关注(: 1=已关注，2=已禁用，4=未关注)
	private Integer attentionStatus;
	//微信用户是否同步 1、未同步；2、已结同步
	private Integer sysWeixinStatus;
	private Department department;
	//1、为启用；2、为停用
	private Integer userState;
	private boolean state;
	
	
	//管理员类型：1、为管理员，2、位普通用户
	private Integer adminType;
	//分店
	private Enterprise enterprise;
	//添加一个父节点
	private User parent;
	private Set<Role> roles;
	private  Set<GrantedAuthority> authorities;
    private  boolean accountNonExpired;
    private  boolean accountNonLocked;
    private  boolean credentialsNonExpired;
    //查看公司数据权限
    private String compnayIds;
    //合同流失审批权限;1、为默认；2、审批
    private Integer approvalCpidStatus;
    //是否用户查询其他公司数据权限：1、默认；2、拥有权限
    private Integer queryOtherDataStatus;
    //对应经理自己买车审批自己的订单、合同流失，1、默认人无权限；2、为有权限
    private Integer selfApproval;
    //利润审批权限 金额
    private Integer approvalMoney;
    //客户业务类型:1、展厅销售；2、网销销售；3、区域；4、后勤；5、其他
    private Integer bussiType;
	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public User() {
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
        sb.append(super.toString()).append(": ");
        sb.append("userId: ").append(this.userId).append("; ");
        sb.append("Password: [PROTECTED]; ").append(this.password).append(": ");
        sb.append("realName: ").append(this.realName).append("; ");
        sb.append("email: ").append(this.email).append("; ");
        sb.append("state: ").append(this.state).append("; ");
        sb.append("AccountNonExpired: ").append(this.isAccountNonExpired()).append("; ");
        sb.append("credentialsNonExpired: ").append(this.isCredentialsNonExpired()).append("; ");
        sb.append("AccountNonLocked: ").append(this.isAccountNonLocked()).append("; ");

        if ( null !=authorities  && !authorities.isEmpty()) {
            sb.append("Granted Authorities: ");

            boolean first = true;
            for (GrantedAuthority auth : authorities) {
                if (!first) {
                    sb.append(",");
                }
                first = false;

                sb.append(auth);
            }
        } else {
            sb.append("Not granted any authorities");
        }
		return super.toString();
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#getAuthorities()
	 */
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return authorities;
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#getUsername()
	 */
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.userId;
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#isAccountNonExpired()
	 */
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#isAccountNonLocked()
	 */
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#isCredentialsNonExpired()
	 */
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	/* (non-Javadoc)
	 * @see org.springframework.security.core.userdetails.UserDetails#isEnabled()
	 */
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}


	public boolean isState() {
		return state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public void setAuthorities(Set<GrantedAuthority> authorities) {
		
		this.authorities = sortAuthorities(authorities);
	}

	public void setAccountNonExpired(boolean accountNonExpired) {
		this.accountNonExpired = accountNonExpired;
	}

	public void setAccountNonLocked(boolean accountNonLocked) {
		this.accountNonLocked = accountNonLocked;
	}

	public void setCredentialsNonExpired(boolean credentialsNonExpired) {
		this.credentialsNonExpired = credentialsNonExpired;
	}
	


	private static SortedSet<GrantedAuthority> sortAuthorities(Collection<GrantedAuthority> authorities) {
	        // Ensure array iteration order is predictable (as per UserDetails.getAuthorities() contract and SEC-717)
	        SortedSet<GrantedAuthority> sortedAuthorities =
	            new TreeSet<GrantedAuthority>(new AuthorityComparator());
	
	        for (GrantedAuthority grantedAuthority : authorities) {
	            sortedAuthorities.add(grantedAuthority);
	        }
	
	        return sortedAuthorities;
	    }

    private static class AuthorityComparator implements Comparator<GrantedAuthority>, Serializable {
        public int compare(GrantedAuthority g1, GrantedAuthority g2) {
            // Neither should ever be null as each entry is checked before adding it to the set.
            // If the authority is null, it is a custom authority and should precede others.
            if (g2.getAuthority() == null) {
                return -1;
            }

            if (g1.getAuthority() == null) {
                return 1;
            }

            return g1.getAuthority().compareTo(g2.getAuthority());
        }
    }

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Integer getUserState() {
		return userState;
	}

	public void setUserState(Integer userState) {
		this.userState = userState;
	}
	public String getWechatId() {
		return wechatId;
	}

	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

	public Integer getAttentionStatus() {
		return attentionStatus;
	}

	public void setAttentionStatus(Integer attentionStatus) {
		this.attentionStatus = attentionStatus;
	}

	public String getPositionIds() {
		return positionIds;
	}

	public void setPositionIds(String positionIds) {
		this.positionIds = positionIds;
	}

	public String getPositionNames() {
		return positionNames;
	}

	public void setPositionNames(String positionNames) {
		this.positionNames = positionNames;
	}


	public Enterprise getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

	public Integer getAdminType() {
		return adminType;
	}

	public void setAdminType(Integer adminType) {
		this.adminType = adminType;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompnayIds() {
		return compnayIds;
	}

	public void setCompnayIds(String compnayIds) {
		this.compnayIds = compnayIds;
	}

	public User getParent() {
		return parent;
	}

	public void setParent(User parent) {
		this.parent = parent;
	}

	public Integer getApprovalCpidStatus() {
		return approvalCpidStatus;
	}

	public void setApprovalCpidStatus(Integer approvalCpidStatus) {
		this.approvalCpidStatus = approvalCpidStatus;
	}

	public Integer getQueryOtherDataStatus() {
		return queryOtherDataStatus;
	}

	public void setQueryOtherDataStatus(Integer queryOtherDataStatus) {
		this.queryOtherDataStatus = queryOtherDataStatus;
	}

	public Integer getSysWeixinStatus() {
		return sysWeixinStatus;
	}

	public void setSysWeixinStatus(Integer sysWeixinStatus) {
		this.sysWeixinStatus = sysWeixinStatus;
	}

	public Integer getSelfApproval() {
		return selfApproval;
	}

	public void setSelfApproval(Integer selfApproval) {
		this.selfApproval = selfApproval;
	}

	public Integer getApprovalMoney() {
		return approvalMoney;
	}

	public void setApprovalMoney(Integer approvalMoney) {
		this.approvalMoney = approvalMoney;
	}

	public Integer getBussiType() {
		return bussiType;
	}

	public void setBussiType(Integer bussiType) {
		this.bussiType = bussiType;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
    
}
