package com.ystech.stat.model;
// Generated 2018-9-28 11:54:13 by Hibernate Tools 4.0.0.Final

/**
 * StaAssessmentindexlevel generated by hbm2java
 */
public class StaAssessmentIndexLevel implements java.io.Serializable {
	private Integer dbid;
	//登记名称
	private String name;
	//初始值
	private Integer beginNum;
	//结束值
	private Integer endnum;
	//公司建议
	private String entSugg;
	//部门建议
	private String depSugg;
	//业务员建议
	private String salSugg;
	//类型：1、优秀；2、合格；3、不合格
	private Integer type;
	//指标类型
	private StaAssessmentIndex staAssessmentIndex;
	private Integer scoreNum;

	public StaAssessmentIndexLevel() {
	}

	public StaAssessmentIndexLevel(String name, Integer beginNum, Integer endnum, String entSugg, String depSugg,
			String salSugg, Integer type, Integer indexId, Integer scoreNum) {
		this.name = name;
		this.beginNum = beginNum;
		this.endnum = endnum;
		this.entSugg = entSugg;
		this.depSugg = depSugg;
		this.salSugg = salSugg;
		this.type = type;
		this.scoreNum = scoreNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getBeginNum() {
		return this.beginNum;
	}

	public void setBeginNum(Integer beginNum) {
		this.beginNum = beginNum;
	}

	public Integer getEndnum() {
		return this.endnum;
	}

	public void setEndnum(Integer endnum) {
		this.endnum = endnum;
	}

	public String getEntSugg() {
		return this.entSugg;
	}

	public void setEntSugg(String entSugg) {
		this.entSugg = entSugg;
	}

	public String getDepSugg() {
		return this.depSugg;
	}

	public void setDepSugg(String depSugg) {
		this.depSugg = depSugg;
	}

	public String getSalSugg() {
		return this.salSugg;
	}

	public void setSalSugg(String salSugg) {
		this.salSugg = salSugg;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}


	public StaAssessmentIndex getStaAssessmentIndex() {
		return staAssessmentIndex;
	}

	public void setStaAssessmentIndex(StaAssessmentIndex staAssessmentIndex) {
		this.staAssessmentIndex = staAssessmentIndex;
	}

	public Integer getScoreNum() {
		return this.scoreNum;
	}

	public void setScoreNum(Integer scoreNum) {
		this.scoreNum = scoreNum;
	}
	public enum StaType{
		excellent("优秀", 1), reachs("达标", 2), failPass("未达标", 3);
	    // 成员变量
	    private String name;
	    private int index;

	    // 构造方法
	    private StaType(String name, int index) {
	        this.name = name;
	        this.index = index;
	    }

	    // 普通方法
	    public static String getName(int index) {
	        for (StaType c : StaType.values()) {
	        if (c.getIndex() == index) {
	            return c.name;
	        }
	        }
	        return null;
	    }

	    // get set 方法
	    public String getName() {
	        return name;
	    }

	    public void setName(String name) {
	        this.name = name;
	    }

	    public int getIndex() {
	        return index;
	    }

	    public void setIndex(int index) {
	        this.index = index;
	    }
	    public static StaType getByValue(int value) {
	    	for (StaType code : values()) {
	    		if (code.getIndex() == value) {
	    			return code;            
	    		}        
	    	}
	    	return null;
	    }

	}
}
