package com.ystech.stat.model;
// Generated 2018-9-21 14:52:38 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * 功能描述：月度留存客户基盘数据，没有月初1:00创建
 * StaCustcomp generated by hbm2java
 */
public class StaCustomerCopy implements java.io.Serializable {

	private Integer dbid;
	//客户ID
	private Integer customerId;
	//创建时时间
	private Date createDate;

	public StaCustomerCopy() {
	}

	public Integer getDbid() {
		return dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}



}
