package com.ystech.stat.customerrecord.model;

// Generated 2018-9-21 14:52:38 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import com.ystech.stat.model.core.StaDateNum;

/**
 * StaCustcomp generated by hbm2java
 */
public class StaCustomerRecordMonth extends StaDateNum implements java.io.Serializable {
	// 日期
	private Date createDate;
	// 到店数
	private Integer comeNum;
	// 到店看车数
	private Integer comeShopNum;
	// 网销到店客户
	private Integer netNum;
	// 到店简单数
	private Integer comeShopCreateFolderNum;
	// 来店建档率
	private Float comeShopCreateFolderNumPer;
	// 来电数
	private Integer phoneNum;
	// 来电看车数
	private Integer phoneShopNum;
	// 来电建档数
	private Integer phoneCreateFolderNum;
	// 来电建档率
	private Float phoneCreateFolderPer;
	//已有客户转登记
	private Integer otherNum;
	//首次进店
	private Integer firstComeNum;

	public StaCustomerRecordMonth(){
		
	}
	
	public StaCustomerRecordMonth(Date date) {
		this.createDate = date;
		this.comeNum = 0;
		this.comeShopNum = 0;
		this.netNum = 0;
		this.comeShopCreateFolderNum = 0;
		this.comeShopCreateFolderNumPer = 0f;
		this.phoneNum = 0;
		this.phoneShopNum = 0;
		this.phoneCreateFolderNum = 0;
		this.phoneCreateFolderPer = 0f;
	}

	public Integer getComeNum() {
		return comeNum;
	}

	public void setComeNum(Integer comeNum) {
		this.comeNum = comeNum;
	}

	public Integer getComeShopNum() {
		return comeShopNum;
	}

	public void setComeShopNum(Integer comeShopNum) {
		this.comeShopNum = comeShopNum;
	}

	public Integer getComeShopCreateFolderNum() {
		return comeShopCreateFolderNum;
	}

	public void setComeShopCreateFolderNum(Integer comeShopCreateFolderNum) {
		this.comeShopCreateFolderNum = comeShopCreateFolderNum;
	}

	public Integer getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(Integer phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Integer getPhoneShopNum() {
		return phoneShopNum;
	}

	public void setPhoneShopNum(Integer phoneShopNum) {
		this.phoneShopNum = phoneShopNum;
	}

	public Integer getPhoneCreateFolderNum() {
		return phoneCreateFolderNum;
	}

	public void setPhoneCreateFolderNum(Integer phoneCreateFolderNum) {
		this.phoneCreateFolderNum = phoneCreateFolderNum;
	}

	public Integer getNetNum() {
		return netNum;
	}

	public void setNetNum(Integer netNum) {
		this.netNum = netNum;
	}

	/**
	 * @return the createDate
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate
	 *            the createDate to set
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return the comeShopCreateFolderNumPer
	 */
	public Float getComeShopCreateFolderNumPer() {
		return comeShopCreateFolderNumPer;
	}

	/**
	 * @param comeShopCreateFolderNumPer
	 *            the comeShopCreateFolderNumPer to set
	 */
	public void setComeShopCreateFolderNumPer(Float comeShopCreateFolderNumPer) {
		this.comeShopCreateFolderNumPer = comeShopCreateFolderNumPer;
	}

	/**
	 * @return the phoneCreateFolderPer
	 */
	public Float getPhoneCreateFolderPer() {
		return phoneCreateFolderPer;
	}

	/**
	 * @param phoneCreateFolderPer
	 *            the phoneCreateFolderPer to set
	 */
	public void setPhoneCreateFolderPer(Float phoneCreateFolderPer) {
		this.phoneCreateFolderPer = phoneCreateFolderPer;
	}

	public Integer getOtherNum() {
		return otherNum;
	}

	public void setOtherNum(Integer otherNum) {
		this.otherNum = otherNum;
	}

	public Integer getFirstComeNum() {
		return firstComeNum;
	}

	public void setFirstComeNum(Integer firstComeNum) {
		this.firstComeNum = firstComeNum;
	}

}
