package com.ystech.weixin.model.sta;

// Generated 2015-10-20 12:04:28 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WeixinStaUsersummary generated by hbm2java
 */
public class UserSummary implements java.io.Serializable {

	private Integer dbid;
	private Date refDate;
	private Integer userSource;
	private Integer newUser;
	private Integer cancelUser;
	private Integer accountId;

	public UserSummary() {
	}

	public UserSummary(Date refDate, Integer userSource,
			Integer newUser, Integer cancelUser, Integer wechatCompanyId) {
		this.refDate = refDate;
		this.userSource = userSource;
		this.newUser = newUser;
		this.cancelUser = cancelUser;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Date getRefDate() {
		return this.refDate;
	}

	public void setRefDate(Date refDate) {
		this.refDate = refDate;
	}

	public Integer getUserSource() {
		return this.userSource;
	}

	public void setUserSource(Integer userSource) {
		this.userSource = userSource;
	}

	public Integer getNewUser() {
		return this.newUser;
	}

	public void setNewUser(Integer newUser) {
		this.newUser = newUser;
	}

	public Integer getCancelUser() {
		return this.cancelUser;
	}

	public void setCancelUser(Integer cancelUser) {
		this.cancelUser = cancelUser;
	}

	public Integer getAccountId() {
		return accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}


}
